<?php
$this->getAllStore();
?>
<!-- 主框架 s -->
<div style="height:90px; z-index:-2; background:#000;"></div>
<div class="newsWrap">
    <div class="newsWrapBg">
        <div class="newsWrapBgTop"><img src="<?php  echo $this->getSkinUrl("images/news_bg.jpg") ?>" alt=""></div>
        <!-- <div class="newsWrapBgBot"><img src="../images/newsBackground_bottom.jpg" alt=""></div> -->
    </div>
    <div class="newsWrapBox">
        <div class="newsWrapTit"><img src="<?php  echo $this->getSkinUrl("images/shopsAdrs_title.png") ?>" alt=""></div>
        <div class="shopsSelect clearfix">
            <span class="ms-fl"><img src="<?php  echo $this->getSkinUrl("images/shopsAdrs_selectTit.png") ?>" alt=""></span>
            	<span class="ms-fl">
            		<select name="" id="">
                        <option value="">上海</option>
                    </select>
            	</span>
        </div>
        <div class="shopListTitle"><img src="<?php  echo $this->getSkinUrl("images/shopsAdrs_listTitle.png") ?>" alt=""></div>
        <ul class="shopsList">
            <li class="clearfix">
                <span class="shopsList_city">1上海</span>
                <span class="shopsList_name">斯伯丁 上海 闵行店</span>
                <span class="shopsList_adrs">闵行区顾戴路80号(虹梅路)</span>
            </li>
            <li class="clearfix">
                <span class="shopsList_city">2上海</span>
                <span class="shopsList_name">斯伯丁 上海 闵行店</span>
                <span class="shopsList_adrs">闵行区顾戴路80号(虹梅路)</span>
            </li>
            <li class="clearfix">
                <span class="shopsList_city">3上海</span>
                <span class="shopsList_name">斯伯丁 上海 闵行店</span>
                <span class="shopsList_adrs">闵行区顾戴路80号(虹梅路)</span>
            </li>
            <li class="clearfix">
                <span class="shopsList_city">4上海</span>
                <span class="shopsList_name">斯伯丁 上海 闵行店</span>
                <span class="shopsList_adrs">闵行区顾戴路80号(虹梅路)</span>
            </li>
            <li class="clearfix">
                <span class="shopsList_city">5上海</span>
                <span class="shopsList_name">斯伯丁 上海 闵行店</span>
                <span class="shopsList_adrs">闵行区顾戴路80号(虹梅路)</span>
            </li>
            <li class="clearfix">
                <span class="shopsList_city">5上海</span>
                <span class="shopsList_name">斯伯丁 上海 闵行店</span>
                <span class="shopsList_adrs">闵行区顾戴路80号(虹梅路)</span>
            </li>
            <li class="clearfix">
                <span class="shopsList_city">5上海</span>
                <span class="shopsList_name">斯伯丁 上海 闵行店</span>
                <span class="shopsList_adrs">闵行区顾戴路80号(虹梅路)</span>
            </li>
            <li class="clearfix">
                <span class="shopsList_city">5上海</span>
                <span class="shopsList_name">斯伯丁 上海 闵行店</span>
                <span class="shopsList_adrs">闵行区顾戴路80号(虹梅路)</span>
            </li>
            <li class="clearfix">
                <span class="shopsList_city">5上海</span>
                <span class="shopsList_name">斯伯丁 上海 闵行店</span>
                <span class="shopsList_adrs">闵行区顾戴路80号(虹梅路)</span>
            </li>
        </ul>
    </div>
</div>
<!-- 主框架 e -->
<script>
    jQuery(function(){
        // $('ul.shopsList li:even').css("background","#282828");
        var $adrLi =  jQuery('ul.shopsList li');
        $adrLi.each(function(){
            var adrLiInd = jQuery(this).index();
            if(adrLiInd%2==0){
                jQuery(this).css("background","#282828");
            }
        });

    });
</script>