<!-- 主框架 s -->
<div style="height:90px; z-index:-2; background:#000;"></div>
<div class="newsWrap">
    <div class="newsWrapBg">
        <div class="newsWrapBgTop"><img src="<?php  echo $this->getSkinUrl("images/news_bg.jpg") ?>" alt=""></div>
    </div>

    <div class="newsWrapBox">
        <div class="newsWrapTit"><img src="<?php  echo $this->getSkinUrl("images/notice_title.png") ?>" alt=""></div>
        <div class="noticeBox">
        	<div class="noticeTime">
        		<img src="<?php  echo $this->getSkinUrl("images/noticeTime.png") ?>" alt="">
        	</div>
        	<div class="noticeCon">
        		<img src="<?php  echo $this->getSkinUrl("images/noticeCon.png") ?>" alt="">
        	</div>
        </div>
    </div>
</div>
<!-- 主框架 e -->
