<script>
	jQuery(function(){
		//设置预览字号
		var _textSize = 80;
		jQuery(".textBox").css("font-size" , _textSize + 'px');
	});
</script>
<!-- 定制背景 -->
<div class="bodyBg_cusMade">
    <img style="width:100%;" src="<?php echo $this->getSkinUrl('images/customMade/cBg2.jpg');  ?>" alt="">
</div>
<!-- 主框架 s -->
<div class="cusMadeCons madeStep_2">
	<div class="cusMadeBox cusMadeCen">
		<div id="playimages" class="play" style="height:600px;">
			<div class="prev"></div>
			<div class="next"></div>

			<div class="prev_n"></div>
			<div class="next_z"></div>

			<!-- 第一套 s -->
			<ul class="big_pic made_1" style="display:none;">

				<!-- <div class="prev"></div>
				<div class="next"></div>

				<div class="prev_n"></div>
				<div class="next_z"></div> -->

				<!-- 遮罩 -->
				<!-- <div class="zz"><img src="<?php  echo $this->getSkinUrl("images/customMade/01.png") ?>" alt="" /></div> -->
				
				<!-- 1-1 -->
		        <li style="z-index:1;">
		        	<div class="imgBox imgPag_1 imgPag_1_1"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/01.png") ?>" alt="" /></div>
		        </li>
		        
		        <!-- 1-2 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_2"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/02.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-3 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_3"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/03.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-4 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_4"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/04.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-5 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_5"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/05.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-6 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_6"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/06.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-7 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_7"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgPag_2 imgPag_2_1"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/07.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-8 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_8"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgPag_2 imgPag_2_2"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/08.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-9 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_9"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgPag_2 imgPag_2_3"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/09.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-10 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_10"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgPag_2 imgPag_2_4"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/10.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-11 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_11"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgPag_2 imgPag_2_5"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/11.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-12 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_12"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgPag_2 imgPag_2_6"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/12.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-13 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_13"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgPag_2 imgPag_2_7"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/13.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-14 -->
		        <li>
		        	<div class="imgBox imgPag_1 imgPag_1_14"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgPag_2 imgPag_2_8"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/14.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-15 -->
		        <li>
		        	<div class="imgBox imgPag_2 imgPag_2_9"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/15.png") ?>" alt="" /></div>
		        </li> 

		        <!-- 1-16 -->
		        <li>
		        	<div class="imgBox imgPag_2 imgPag_2_10"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/16.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-17 -->
		        <li>
		        	<div class="imgBox imgPag_2 imgPag_2_11"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/17.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-18 -->
		        <li>
		        	<div class="imgBox imgPag_2 imgPag_2_12"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/18.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-19 -->
		        <li>
		            <div class="imgBox imgPag_2 imgPag_2_13"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/19.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-20 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_15"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_14"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/20.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-21 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_16"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_15"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/21.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-22 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_17"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_16"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/22.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-23 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_18"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_17"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/23.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-24 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_19"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_18"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/24.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-25 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_20"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_19"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/25.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-26 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_21"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_20"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/26.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-27 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_22"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_21"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/27.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-28 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_23"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_22"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/28.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-29 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_24"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_23"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/29.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-30 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_25"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgPag_2 imgPag_2_24"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_2.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/30.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-31 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_26"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/31.png") ?>" alt="" /></div>
		        </li>

		        <!-- 1-32 -->
		        <li>
		            <div class="imgBox imgPag_1 imgPag_1_27"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgPer_1.jpg") ?>" alt="" /></div>
		            <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/32.png") ?>" alt="" /></div>
		        </li>
			</ul>
		    <!-- 第一套 e -->
			

			<!-- 第二套 s -->
		    <ul class="big_pic">
				<!-- 遮罩 -->
				<!-- <div class="zz"><img src="<?php  echo $this->getSkinUrl("images/customMade/01.png") ?>" alt="" /></div> -->
				
				<!-- 2-1 -->
				<li style="z-index:1;">
		        	<div class="textBox textPag_1 textPag_1_1">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/01.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-2 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_2">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/02.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-3 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_3">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/03.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-4 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_4">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/04.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-5 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_5">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/05.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-6 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_6">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/06.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-7 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_7">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/07.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-8 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_8">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_1">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/08.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-9 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_9">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_2">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/09.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-10 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_10">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_3">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/10.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-11 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_11">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_4">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/11.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-12 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_12">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_5">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/12.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-13 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_13">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_6">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/13.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-14 -->
				<li>
		        	<div class="textBox textPag_2 textPag_2_7">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/14.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-15 -->
				<li>
		        	<div class="textBox textPag_2 textPag_2_8">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/15.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-16 -->
				<li>
		        	<div class="textBox textPag_2 textPag_2_9">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/16.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-17 -->
				<li>
		        	<div class="textBox textPag_2 textPag_2_10">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/17.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-18 -->
				<li>
		        	<div class="textBox textPag_2 textPag_2_11">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/18.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-19 -->
				<li>
		        	<div class="textBox textPag_2 textPag_2_12">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/19.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-20 -->
				<li>
		        	<div class="textBox textPag_2 textPag_2_13">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/20.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-21 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_14">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_14">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/21.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-22 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_15">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_15">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/22.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-23 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_16">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_16">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/23.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-24 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_17">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_17">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/24.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-25 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_18">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_18">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/25.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-26 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_19">Spalding</div>
		        	<div class="textBox textPag_2 textPag_2_19">ABCDEFG</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/26.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-27 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_20">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/27.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-28 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_21">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/28.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-29 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_22">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/29.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-30 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_23">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/30.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-31 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_24">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/31.png") ?>" alt="" /></div>
		        </li>

		        <!-- 2-32 -->
				<li>
		        	<div class="textBox textPag_1 textPag_1_25">Spalding</div>
		        	<div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_n/32.png") ?>" alt="" /></div>
		        </li>

		    </ul>
		    
		</div>
	</div>

	<!-- 右侧设置通栏 s -->
	<div class="cusMadeBox cusMadeRig">
        <div class="madeBoxVal">
            <h1>SPALDING 74-604 ID</h1>
            <h2>价格：￥220</h2>
        </div>
        <div class="madeP_btn madeP_1_btn madeP_btn_now">P1</div>
        <div class="madeP_btn madeP_2_btn">P2</div>
        
        <!-- p1 -->
        <div class="madeBoxCons madeBoxCons_p1">
            <h3>可定制球皮</h3>
            <p class="madeTs">选择添加图案或个性签名</p>
            <p class="madeSn">（每块定制球皮只可选择以下一种定制）</p>
            <!-- 定制参数 -->
            <dl class="madeBoxFuns">
                <dd class="madeKindTit madeKindTitImg madeNow">定制图案</dd>
                <dt class="madeKindCons madeKindImg">
                    <h5>***注意***</h5>
                    <p>支持jpg、gif、png格式，单张图片大小2M-8M</p>
                </dt>
                <dd class="madeKindTit madeKindTitTex">定制文字</dd>
                <dt class="madeKindCons madeKindTex">
                    <div class="madeTextInp">
                        <input type="text" class="madeTextInpBox" placeholder="请输入定制文字">
                    </div>
                    <p>请选择字号：</p>
                    <div id="product-options-wrapper" class="madeKindTexSpan">
                      <div class="sale-num">
                        <input type="radio" class="required-entry super-attribute-select" id="attribute2098" name="attribute2098" data-input="kinds" value="53">
                        <span class="sale_kind setSize_40" for="attribute2098" name="attribute2098">大号字体</span>
                        <input type="radio" class="required-entry super-attribute-select" id="attribute2097" name="attribute2097" data-input="kinds" value="54">
                        <span class="sale_kind setSize_30" for="attribute2097" name="attribute2097">中号字体</span>
                        <input type="radio" class="required-entry super-attribute-select" id="attribute2096" name="attribute2096" data-input="kinds" value="55">
                        <span class="sale_kind setSize_20" for="attribute2096" name="attribute2096">小号字体</span>
                      </div>
                    </div>
                </dt>
                <dd class="madeKindTit madeKindTitNon">空白</dd>
            </dl>
            
        </div>

        <!-- p2 -->
        <div class="madeBoxCons madeBoxCons_p2" style="display:none;">
            <h3>可定制球皮</h3>
            <p class="madeTs">选择添加图案或个性签名</p>
            <p class="madeSn">（每块定制球皮只可选择以下一种定制）</p>
            <!-- 定制参数 -->
            <dl class="madeBoxFuns">
                <dd class="madeKindTit madeKindTitImg madeNow">定制图案</dd>
                <dt class="madeKindCons madeKindImg">
                    <h5>***注意***</h5>
                    <p>支持jpg、gif、png格式，单张图片大小2M-8M</p>
                </dt>
                <dd class="madeKindTit madeKindTitTex">定制文字</dd>
                <dt class="madeKindCons madeKindTex">
                    <div class="madeTextInp">
                        <input type="text" class="madeTextInpBox" placeholder="请输入定制文字">
                    </div>
                    <div id="product-options-wrapper" class="madeKindTexSpan">
                      <div class="sale-num">
                        <input type="radio" class="required-entry super-attribute-select" id="attribute2098" name="attribute2098" data-input="kinds" value="53">
                        <span class="sale_kind setSize_40" for="attribute2098" name="attribute2098">大号字体</span>
                        <input type="radio" class="required-entry super-attribute-select" id="attribute2097" name="attribute2097" data-input="kinds" value="54">
                        <span class="sale_kind setSize_30" for="attribute2097" name="attribute2097">中号字体</span>
                        <input type="radio" class="required-entry super-attribute-select" id="attribute2096" name="attribute2096" data-input="kinds" value="55">
                        <span class="sale_kind setSize_20" for="attribute2096" name="attribute2096">小号字体</span>
                      </div>
                    </div>
                </dt>
                <dd class="madeKindTit madeKindTitNon">空白</dd>
            </dl>
            
        </div>

		<div class="madeSubmit">
                <button class="submitY">完成此次定制</button>
                <button class="submitN">重置此次定制</button>
            </div>
        <div class="madeFuns">
            <button>加入购物车</button>
        </div>
    </div>
    <!-- 右侧设置通栏 e -->
</div>

<!-- 主框架 e -->


<div class="madeBotmSn">
    <h1>定制专属篮球</h1>
    <p>斯伯丁74-604“掌控”系列的经典之作，销量之王，性价比之王，超强PU超耐磨，室内外通用，<br>恰到好处的粘度让你轻松“掌控”比赛！</p>
</div>
