<?php
    // Check if current Magento version includes Persistent Shopping Cart Extension
    $isPersistantShoppingCartEnabled = Mage::getStoreConfigFlag('persistent/options/enabled');
    $isContextCheckout = 0;
    if ($isPersistantShoppingCartEnabled) {
        $html = $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml();
        $isContextCheckout = Mage::helper('checkout')->isContextCheckout();
    } else {
        $html = $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml();
    }
?>
<div class="bodyBg"><img src='<?php echo $this->getSkinUrl("images/home/20141210002.jpg") ?>' alt=""></div>

<div class="account-create">
<!--    <div class="page-title">-->
<!--        <h1>--><?php //echo $this->__('Create an Account') ?><!--</h1>-->
<!--    </div>-->
<!--    --><?php //echo $this->getChildHtml('form_fields_before')?>
<!--    --><?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
<!--    --><?php //echo $this->getChildHtml('paypalauth.register'); ?>
    <div style="height:110px; z-index:-2;"></div>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="spaldingMain">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <div class="regTit">
                注册新用户
                <span class="ms-fr">我已经注册了，现在就&nbsp;<a href="login.html">登录</a></span>
                <div class="clear"></div>
            </div>
                    <label for="email_address" class="required">
                        <div class="regBox clearfix">
                            <span class="regBoxTit ms-fl">创建理想登录名 *</span>
			                <span class="regBoxWrap ms-fl">
                                    <input type="text" id="firstname" name="firstname" value="" title="收件人姓名" maxlength="255" class="regBoxInp input-text required-entry">
				            <span class="regBoxWrapSn">例如：张三，zhangsan，zhang,shan。使用（汉字、字母、下划线等字符），数字不能第一个字符出现</span>
			                </span>
                        </div>
                    </label>

            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>


                    <div class="regBox clearfix">
<!--                        <label for="password" class="required"><em>*</em>--><?php //echo $this->__('Password') ?><!--</label>-->
                        <span class="regBoxTit ms-fl">设定登录密码 *</span>
                        <span class="regBoxWrap ms-fl">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="regBoxInp input-text required-entry validate-password" />
                        </span>
                    </div>
                    <div class="regBox clearfix">
<!--                        <label for="confirmation" class="required"><em>*</em>--><?php //echo $this->__('Confirm Password') ?><!--</label>-->
                        <span class="regBoxTit ms-fl">请再次输入密码 *</span>
                        <span class="regBoxWrap ms-fl">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="regBoxInp input-text required-entry validate-cpassword" />
                        </span>
                    </div>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

            <div class="regBox clearfix">
                <span class="regBoxTit ms-fl">电子邮件E-mail *</span>
			<span class="regBoxWrap ms-fl">
<!--				<input type="text" class="regBoxInp"><br>-->
                <input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="regBoxInp input-text validate-email required-entry" /><br>
				<span class="regBoxWrapSn">您必须提供一个正确电子邮箱地址，否则账号无法激活</span>
			</span>
            </div>
            <div class="regBox clearfix">
                <span class="regBoxTit ms-fl">服务条款</span>
			<span class="regBoxWrap ms-fl">
				<span class="regBoxWrapSn">请检查以上您输入的个人账户信息（内容可以随意更改）,并阅读以下服务条款。</span>
				<div class="regRuls">本协议是您与斯伯丁中国商城网站（简称“本站”，网址：www.SPALDINGCHINA.com）所有者（以下简称为“斯伯丁中国商城”）之间就斯伯丁商城网站服务等相关事宜所订立的契约，请您仔细阅读本注册协议，您点击“同意以下协议，提交”按钮后，本协议即构成对双方有约束力的法律文件。第1条 本站服务条款的确认和接纳1.1	本站的各项电子服务的所有权和运作权归斯伯丁中国有限公司所有。用户同意所有协议是您与斯伯丁中国商城网站（简称“本站”，网址：www.SPALDINGCHINA.com）所有者（以下简称为“斯伯丁中国商城”）之间就斯伯丁商城网站服务等相关事宜所订立的契约，请您仔细阅读本注册协议，您点击“同意以下协议，提交”按钮后，本协议即构成对双方有约束力的法律文件。第1条 本站服务条款的确认和接纳1.1	本站的各项电子服务的所有权和运作权归斯伯丁中国有限公司所有。用户同意所有</div>
				<span class="regBoxWrapSn" style="margin:10px 0;">点击下面的“我接受”，及表示您同意接受上面的<font style="color:#666;text-decoration:underline;">条款</font>。</span><br>
                <?php if ($this->isNewsletterEnabled()): ?>
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                        <span class="regBoxWrapSn">发送注册信息到我的注册邮箱？</span><br>
<!--                    <label for="is_subscribed">--><?php //echo $this->__('Sign Up for Newsletter') ?><!--</label>-->
                <?php endif ?>
                <button type="submit" title="<?php echo $this->__('注册') ?>" class="rulAgree button">我接受,并注册</button><br>
				<span>* 为必填项</span>
			</span>
            </div>


<!--        <div class="buttons-set">-->
<!--            <p class="required">--><?php //echo $this->__('* Required Fields') ?><!--</p>-->
<!--            <p class="back-link"><a href="--><?php //echo $this->escapeUrl($this->getBackUrl()) ?><!--" class="back-link"><small>&laquo; </small>--><?php //echo $this->__('Back') ?><!--</a></p>-->
<!--            <button type="submit" title="--><?php //echo $this->__('Submit') ?><!--" class="button"><span><span>--><?php //echo $this->__('Submit') ?><!--</span></span></button>-->
<!--        </div>-->
        <?php if ($isContextCheckout): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
    <script>
        $(function(){
            setTimeout(function(){
                var sliderH = $('.spalding_index_slider img').height();
                //alert(sliderH);
                $('#focus').css("height",sliderH);
                //$('.footer').css("display","block")
            },100);

            $('.searchBtn').mouseover(function(){
                $(this).parents().find('.dropDown_search').slideDown();
            });

            $('.dropDownBg').on("click",function(){
                $(this).parent('.dropDown_search').slideUp();
            });
            $('.dropClose').on("click",function(){
                $(this).parent('.dropDown_search').slideUp();
            });

        });

    </script>
</div>
