<?php $this->initView(); ?>
<?php $_product = $this->getProduct(); ?>

<?php
	$productImageHelper = Mage::helper('product');
?>

<!-- 定制图案 -->
<div class="madeStepImg" style="display:none;">
    <img id="img_grip" style="position:absolute;opacity:0; z-index:100; cursor:pointer;" src="<?php echo $productImageHelper->getCustomMadeImage('grip.png');  ?>" />
    <div class="cusMadeBox cusMadeCen cusMadeCen_img">
        <div class="step_2_Fun" id="formBtn">
            <div class="step_2_FunBg">
                <div class="select_P1">
                    <img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/step_2_Bgball.png');  ?>" alt="">
                </div>
                <div class="select_P2" style="display: none;">
                    <img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/step_2_Bgball2.png');  ?>" alt="">
                </div>
            </div>
            <div class="step_2_funBtn">
                <input type="file" onchange="previewImage(this,'avatar')" id="shopSetFile_1" name="file" style="display:none ">
                <input type="button" onclick="shopSetFile_1.click();" class="step_2_funBtn_1">
            </div>

        </div>
        <div class="step_2_wrap" id="imgFuns" style="opacity:0; position:relative;">
            <!--<div class="portrait_revolve">
                <span>
                    <input type="file" onchange="previewImage(this,'avatar')" id="shopSetFile_2" name="file" style="display:none ">
                    <input type="button" onclick="shopSetFile_2.click();" value="重新添加" class="step_2_funBtn_2">
                </span>


            </div>-->
            <div class="funBall">
                <div class="select_P1">
                    <img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/step_2_funbal-1.png');  ?>" alt="">
                </div>
                <div class="select_P2" style="display: none;">
                    <img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/step_2_funbal-2.png');  ?>" alt="">
                </div>
            </div>

            <div id="cut_div" style="width:705px; height:329px; position:absolute;cursor:pointer;overflow:hidden;">
                <table style="border-collapse: collapse; z-index: 10; filter: alpha(opacity=65); position: relative; left: 0px; top: 0px; width: 705px;  height: 400px; opacity: 0.65; " cellspacing="0" cellpadding="0" border="0" unselectable="on">
                    <tr>
                        <td style="height: 50px;" colspan="3"></td>
                    </tr>
                    <tr>
                        <td style="width: 52px;"></td>
                        <td style="width: 316px; height: 186px;"></td>
                        <td style="width: 52px;"></td>
                    </tr>
                    <tr>
                        <td style="height: 117px;" colspan="3"></td>
                    </tr>
                </table>
                <img id="avatar" style="position:relative; top:-332px; left:0"  src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/step_2_Bgball.png');  ?>"  />
            </div>


            <div class="imgFuns">

                <div style="position:absolute;">
                    <span><img style="margin-top: 5px; cursor:pointer;"  src="<?php echo $productImageHelper->getCustomMadeImage('tomin.png');  ?>" alt="图片缩小" onclick="imageresize(false)" /></span>
                    <span><img id="img_track" style="width: 500px; height: 4px;" src="<?php echo $productImageHelper->getCustomMadeImage('track.png');  ?>" /></span>
                    <span><img style="margin-top: 5px; cursor:pointer;" src="<?php echo $productImageHelper->getCustomMadeImage('tomax.png');  ?>" alt="图片放大" onclick="imageresize(true)" /></span>
                </div>

            </div>

        </div>

    </div>
</div>
<!-- 定制文本 -->
<div class="madeStepTex" style="display:none;">
    <div class="cusMadeBox cusMadeCen">
        <div class="madeTex_ball">
            <div class="select_P1">
                <img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/madeNone_1.png'); ?>" alt="">
            </div>
            <div class="select_P2" style="display: none;">
                <img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/madeNone_2.png'); ?>" alt="">
            </div>
        </div>
        <div class="madeTexWrap">
            <div class="select_P1" id="textMade_P1"></div>
            <div class="select_P2" id="textMade_P2" style="display: none;"></div>
            <div class="select_P3" id="textMade_P3" style="display: none;"></div>
            <div class="select_P4" id="textMade_P4" style="display: none;"></div>
        </div>
    </div>
</div>

<!-- 定制队徽 -->
<div class="madeStepEmb" style="display:none;">
    <div class="cusMadeBox cusMadeCen">
        <div class="madeTex_ball">
            <div class="select_P1">
                <img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/madeNone_1.png'); ?>" alt="">
            </div>
            <div class="select_P2" style="display: none;">
                <img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/madeNone_2.png'); ?>" alt="">
            </div>
        </div>
        <div class="madeEmbWrap_1">
              <img src=""/>
        </div>
        <div class="madeEmbWrap_2">
              <img src=""/>
        </div>
    </div>
    <div class="teamEmblem">
        <div class="embTit">选择NBA队徽</div>
        <div class="embCon clearfix">
            <div class="embCon-tab1">
                <?php
                   $_arrEmb = array('lakers','warriors','76ers','blazers','celtics','spurs','bucks','heat','thunder');
                   for ($_i = 1; $_i <= count($_arrEmb); $_i++): ?>
                    <div class="embImg <?php echo  $_i > 5 ? 'second' : 'first';?>">
                        <img src="<?php echo $this->getSkinUrl('imagesEmblem/'.sprintf('%02d', $_i).'-'.$_arrEmb[$_i-1].'-1-black.png'); ?>"  class="embDefault" alt="">
                        <img src="<?php echo $this->getSkinUrl('imagesEmblem/'.sprintf('%02d', $_i).'-'.$_arrEmb[$_i-1].'-1-blue.png'); ?>"  class="embSelected" alt="">
                    </div>
                    <div class="embImg <?php echo  $_i > 5 ? 'second' : 'first'; ?>">
                        <img src="<?php echo $this->getSkinUrl('imagesEmblem/'.sprintf('%02d', $_i).'-'.$_arrEmb[$_i-1].'-2-black.png'); ?>"  class="embDefault" alt="">
                        <img src="<?php echo $this->getSkinUrl('imagesEmblem/'.sprintf('%02d', $_i).'-'.$_arrEmb[$_i-1].'-2-blue.png'); ?>"  class="embSelected" alt="">
                    </div>
                <?php endfor; ?>
            </div>

            <div class="embCon-tab2">
                <?php
                    $_arrEmb = array('lakers','warriors','76ers','blazers','celtics','spurs','bucks','heat','thunder');
                    for ($_i = 1; $_i <= count($_arrEmb); $_i++): ?>
                        <div class="embImg <?php echo  $_i > 5 ? 'second' : 'first'; ?>">
                        <img src="<?php echo $this->getSkinUrl('imagesEmblem/'.sprintf('%02d', $_i).'-'.$_arrEmb[$_i-1].'-1-color.png'); ?>"  class="embDefault" alt="">
                        <img src="<?php echo $this->getSkinUrl('imagesEmblem/'.sprintf('%02d', $_i).'-'.$_arrEmb[$_i-1].'-1-blue.png'); ?>"  class="embSelected" alt="">
                    </div>
                    <div class="embImg <?php echo  $_i > 5 ? 'second' : 'first'; ?>">
                        <img src="<?php echo $this->getSkinUrl('imagesEmblem/'.sprintf('%02d', $_i).'-'.$_arrEmb[$_i-1].'-2-color.png'); ?>"  class="embDefault" alt="">
                        <img src="<?php echo $this->getSkinUrl('imagesEmblem/'.sprintf('%02d', $_i).'-'.$_arrEmb[$_i-1].'-2-blue.png'); ?>"  class="embSelected" alt="">
                    </div>
                <?php endfor; ?>
            </div>
        </div>

        <div class="embBtn">
            <img src="<?php echo $this->getSkinUrl('imagesEmblem/button-left-1.png'); ?>" class="embBtn_prev" alt="">
            <img src="<?php echo $this->getSkinUrl('imagesEmblem/button-right-1.png'); ?>" class="embBtn_next" alt="">
        </div>
        <div class="switchEmbTab"><span class="embMonochrome active">单色</span><span class="embColour">彩色</span></div>
    </div>
</div>

<!-- 空白 -->
<div class="madeStepNone">
<div class="cusMadeBox cusMadeCen">
<div class="madeTex_ball">
<div class="select_P1">
<img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/madeNone_1.png'); ?>" alt="">
</div>
<div class="select_P2" style="display: none;">
<img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku().'/madeNone_2.png'); ?>" alt="">
</div>
</div>
</div>
</div>

<div class="select_N select_N1" style="display: none;"></div>
<div class="select_N select_N2" style="display: none;"></div>
<div class="viewMade" id="viewMadeFun"><button type="button"><img src="<?php  echo $productImageHelper->getCustomMadeImage("2019-viewMade.png") ?>" alt=""></button></div>
