<!-- 定制图案 -->
<div class="madeStepImg">
    <img id="img_grip" style="position:absolute;opacity:0; z-index:100; cursor:pointer;" src="<?php echo $this->getSkinUrl('images/customMade/grip.png');  ?>" />
    <div class="cusMadeBox cusMadeCen">
        <div class="step_2_Fun" id="formBtn">
            <div class="step_2_FunBg">
                <div class="select_ball_P1">
                    <img src="<?php echo $this->getSkinUrl('images/customMade/step_2_Bgball.png');  ?>" alt="">
                </div>
                <div class="select_ball_P2" style="display: none;">
                    <img src="<?php echo $this->getSkinUrl('images/customMade/imgBall_y/17.png');  ?>" alt="">
                </div>
            </div>
            <div class="step_2_funBtn">
                <input type="file" onchange="previewImage(this,'avatar')" id="shopSetFile_1" name="file" accept="image/gif, image/jpeg" style="display:none ">
                <input type="button" onclick="shopSetFile_1.click();" class="step_2_funBtn_1">
            </div>

        </div>
        <div class="step_2_wrap" id="imgFuns" style="opacity:0; position:relative;">
            <div class="portrait_revolve">
                <span>
                    <a href="javascript:;" class="revol_left_txt" onClick="avatarrotateleft();"><img src="<?php echo $this->getSkinUrl('images/customMade/rotLeft.png');  ?>" alt=""></a>
                </span>

                <span>
                    <input type="file" onchange="previewImage(this,'avatar')" id="shopSetFile_2" name="file" style="display:none ">
                    <input type="button" onclick="shopSetFile_2.click();" value="重新添加" class="step_2_funBtn_2">
                </span>

                <span>
                    <a href="javascript:;" class="revol_right_txt" onClick="avatarrotateright();"><img src="<?php echo $this->getSkinUrl('images/customMade/rotRig.png');  ?>" alt=""></a>
                </span>
            </div>
            <div class="funBall">
                <div class="select_ball_P1">
                    <img src="<?php echo $this->getSkinUrl('images/customMade/step_2_funball.png');  ?>" alt="">
                </div>
                <div class="select_ball_P2" style="display: none;">
                    <img src="<?php echo $this->getSkinUrl('images/customMade/imgBall_y/17.png');  ?>" alt="">
                </div>
            </div>

            <div id="cut_div" style="width:400px; height:400px; border-radius:200px; overflow: hidden; position:absolute; cursor:pointer;">
                <table style="border-collapse: collapse; z-index: 10; filter: alpha(opacity=75); position: relative; left: 0px; top: 0px; width: 400px;  height: 400px; opacity: 0.75; border-radius:200px; overflow:hidden;" cellspacing="0" cellpadding="0" border="0" unselectable="on">
                    <tr>
                        <td style="background: #000000; height: 97px;" colspan="3"></td>
                    </tr>
                    <tr>
                        <td style="background: #000000; width: 52px;"></td>
                        <td style="border: 1px dashed #ffffff; width: 296px; height: 186px;"></td>
                        <td style="background: #000000; width: 52px;"></td>
                    </tr>
                    <tr>
                        <td style="background: #000000; height: 117px;" colspan="3"></td>
                    </tr>
                </table>
                <img id="avatar" style="position:relative; top:-400px; left:0px"  src="<?php echo $this->getSkinUrl('images/customMade/source.jpg');  ?>" />
            </div>


            <div class="imgFuns">

                <div style="position:absolute;">
                    <span><img style="margin-top: 5px; cursor:pointer;"  src="<?php echo $this->getSkinUrl('images/customMade/tomin.png');  ?>" alt="图片缩小" onclick="imageresize(false)" /></span>
                    <span><img id="img_track" style="width: 200px; height: 4px;" src="<?php echo $this->getSkinUrl('images/customMade/track.png');  ?>" /></span>
                    <span><img style="margin-top: 5px; cursor:pointer;" src="<?php echo $this->getSkinUrl('images/customMade/tomax.png');  ?>" alt="图片放大" onclick="imageresize(true)" /></span>
                </div>

            </div>

        </div>

    </div>
</div>
<!-- 定制文本 -->
<div class="madeStepTex" style="display:none;">
    <div class="cusMadeBox cusMadeCen">
        <div class="madeTex_ball">
            <div class="select_ball_P1">
                <img src="<?php echo $this->getSkinUrl('images/customMade/madeTexBg.png'); ?>" alt="">
            </div>
            <div class="select_ball_P2" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/customMade/imgBall_n/17.png'); ?>" alt="">
            </div>
        </div>
        <div class="madeTexWrap">
            spadling
        </div>
    </div>
</div>
<!-- 空白 -->
<div class="madeStepNone" style="display:none;">
    <div class="cusMadeBox cusMadeCen">
        <div class="madeTex_ball">
            <div class="select_ball_P1">
                <img src="<?php echo $this->getSkinUrl('images/customMade/madeTexBg.png'); ?>" alt="">
            </div>
            <div class="select_ball_P2" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/customMade/imgBall_y/17.png'); ?>" alt="">
            </div>
        </div>
    </div>
</div>


