<?php $this->initView(); ?>
<?php $_product = $this->getProduct(); ?>
<?php 
	$productImageHelper = Mage::helper('product');
?>
<div class="cusMadeBox cusMadeCen">
    <div id="playimages" class="play" style="height:600px;">
        <div class="prev"></div>
        <div class="next"></div>

        <div class="prev_n_top"></div>
        <div class="next_z_top"></div>

        <div class="prev_n"></div>
        <div class="next_z"></div>

        <div class="viewBack viewMade"><button type="button"><img src="<?php  echo $productImageHelper->getCustomMadeImage("viewMadeBack.png") ?>" alt=""></button></div>


        
        <?php if ($this->getTypeP1() == 1 && $this->getTypeP2() == 1): ?>
        
        <!-- 第一套 s -->
        <!-- 图片-图片 -->
        <ul class="big_pic">
            <?php
            $_arrP1 = array(1,2,3,4,5,6,7,8,9,10,11,12,13,14,21,22,23,24,25,26,27,28,29,30,31,32);
            $_arrP2 = array(7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26);
            for ($_i = 1; $_i <= 32; $_i++): ?>

                <?php if($_i == 1): ?>
                    <li style="z-index:1;">
                <?php else: ?>
                    <li>
                <?php endif; ?>

                <!-- P1  -->
                <?php if(in_array($_i, $_arrP1)): ?>
                    <div class="imgBox imgPag_1 imgPag_1_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P1() ?>" alt="" /></div>
                <?php endif; ?>

                <!-- P2  -->
                <?php if(in_array($_i, $_arrP2)): ?>
                    <div class="imgBox imgPag_2 imgPag_2_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P2() ?>" alt="" /></div>
                <?php endif; ?>

                    <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_tt/".substr(strval($_i+100),1,3).".png") ?>" alt="" /></div>
                </li>

            <?php endfor; ?>
            
        </ul>
        <!-- 第一套 e -->

        
        <?php elseif($this->getTypeP1() == 2 && $this->getTypeP2() == 2): ?>
        <!-- 第二套 s -->
        <!-- 文字-文字 -->
        <ul class="big_pic">
            <?php
            $_arrP1 = array(1,2,3,4,5,6,7,8,9,10,11,12,13,21,22,23,24,25,26,27,28,29,30,31,32);
            $_arrP2 = array(13,14,15,16,17,18,19,20,21,22,23,24,25,26);
            for ($_i = 1; $_i <= 32; $_i++): ?>

                <?php if($_i == 1): ?>
                    <li style="z-index:1;">
                <?php else: ?>
                    <li>
                <?php endif; ?>

                <!-- P1  -->
                <?php if(in_array($_i, $_arrP1)): ?>
                    <?php if($this->getContent3P1() == 4): ?>
                        <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "><?php echo $this->getContent1P1() ?></div>
                        <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> towLine_view_1"><?php echo $this->getContent2P1() ?></div>
                    <?php else: ?>
                        <div class="textBox textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "><?php echo $this->getContent1P1() ?></div>
                    <?php endif; ?>
                <?php endif; ?>

                <!-- P2  -->
                <?php if(in_array($_i, $_arrP2)): ?>
                    <?php if($this->getContent3P2() == 4): ?>
                        <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>"><?php echo $this->getContent1P2() ?></div>
                        <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?> towLine_view_2"><?php echo $this->getContent2P2() ?></div>
                    <?php else: ?>
                        <div class="textBox textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>"><?php echo $this->getContent1P2() ?></div>
                    <?php endif; ?>
                <?php endif; ?>

                    <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_n/".substr(strval($_i+100),1,3).".png") ?>" alt="" /></div>
                </li>

            <?php endfor; ?>
        </ul>
        <!-- 第二套 e -->

        <?php elseif($this->getTypeP1() == 1 && $this->getTypeP2() == 2): ?>
        
        <!-- 第三套 s -->
        <!-- 图片-文字 -->
        <ul class="big_pic">
            <?php
            $_arrP1 = array(1,2,3,4,5,6,7,8,9,10,11,12,13,14,21,22,23,24,25,26,27,28,29,30,31,32);
            $_arrP2 = array(13,14,15,16,17,18,19,20,21,22,23,24,25,26);
            for ($_i = 1; $_i <= 32; $_i++): ?>

                <?php if($_i == 1): ?>
                    <li style="z-index:1;">
                <?php else: ?>
                    <li>
                <?php endif; ?>

                <!-- P1  -->
                <?php if(in_array($_i, $_arrP1)): ?>
                    <div class="imgBox imgPag_1 imgPag_1_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P1() ?>" alt="" /></div>
                    
                <?php endif; ?>

                <!-- P2  -->
                <?php if(in_array($_i, $_arrP2)): ?>
                    <?php if($this->getContent3P2() == 4): ?>
                        <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>"><?php echo $this->getContent1P2() ?></div>
                        <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?> towLine_view_2"><?php echo $this->getContent2P2() ?></div>
                    <?php else: ?>
                        <div class="textBox textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>"><?php echo $this->getContent1P2() ?></div>
                    <?php endif; ?>
                <?php endif; ?>

                    <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_tz/".substr(strval($_i+100),1,3).".png") ?>" alt="" /></div>
                </li>

            <?php endfor; ?>
            
        </ul>
        <!-- 第三套 e -->

        
        <?php elseif($this->getTypeP1() == 2 && $this->getTypeP2() == 1): ?>
        <!-- 第四套 s -->
        <!-- 文字-图片 -->
        <ul class="big_pic">
            <?php
            $_arrP1 = array(1,2,3,4,5,6,7,8,9,10,11,12,13,21,22,23,24,25,26,27,28,29,30,31,32);
            $_arrP2 = array(8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26);
            for ($_i = 1; $_i <= 32; $_i++): ?>

                <?php if($_i == 1): ?>
                    <li style="z-index:1;">
                <?php else: ?>
                    <li>
                <?php endif; ?>

                <!-- P1  -->
                <?php if(in_array($_i, $_arrP1)): ?>
                    <?php if($this->getContent3P1() == 4): ?>
                        <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "><?php echo $this->getContent1P1() ?></div>
                        <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> towLine_view_1"><?php echo $this->getContent2P1() ?></div>
                    <?php else: ?>
                        <div class="textBox textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "><?php echo $this->getContent1P1() ?></div>
                    <?php endif; ?>
                <?php endif; ?>

                <!-- P2  -->
                <?php if(in_array($_i, $_arrP2)): ?>
                    <div class="imgBox imgPag_2 imgPag_2_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P2() ?>" alt="" /></div>
                <?php endif; ?>

                    <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_zt/".substr(strval($_i+100),1,3).".png") ?>" alt="" /></div>
                </li>

            <?php endfor; ?>
            
        </ul>
        <!-- 第四套 e -->
        
        
        <?php elseif($this->getTypeP1() == 1 && ($this->getTypeP2() != 1 && $this->getTypeP2() != 2)): ?>
        <!-- 第五套 s -->
        <!-- 图片-空 -->
        <ul class="big_pic">
            <?php
            $_arrP1 = array(1,2,3,4,5,6,7,8,9,10,11,12,13,14,21,22,23,24,25,26,27,28,29,30,31,32);

            for ($_i = 1; $_i <= 32; $_i++): ?>

                <?php if($_i == 1): ?>
                    <li style="z-index:1;">
                <?php else: ?>
                    <li>
                <?php endif; ?>

                <!-- P1  -->
                <?php if(in_array($_i, $_arrP1)): ?>
                    <div class="imgBox imgPag_1 imgPag_1_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P1() ?>" alt="" /></div>
                <?php endif; ?>

                    <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_tk/".substr(strval($_i+100),1,3).".png") ?>" alt="" /></div>
                </li>

            <?php endfor; ?>
            
        </ul>
    

        <!-- 第五套 e -->
        
        
        <?php elseif($this->getTypeP1() == 2 && ($this->getTypeP2() != 1 && $this->getTypeP2() != 2)): ?>
        <!-- 第六套 s -->
        <!-- 文字-空 -->
        <ul class="big_pic">
            <?php
            $_arrP1 = array(1,2,3,4,5,6,7,8,9,10,11,12,13,21,22,23,24,25,26,27,28,29,30,31,32);

            for ($_i = 1; $_i <= 32; $_i++): ?>

                <?php if($_i == 1): ?>
                    <li style="z-index:1;">
                <?php else: ?>
                    <li>
                <?php endif; ?>

                <!-- P1  -->
                <?php if(in_array($_i, $_arrP1)): ?>
                    <?php if($this->getContent3P1() == 4): ?>
                        <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "><?php echo $this->getContent1P1() ?></div>
                        <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> towLine_view_1"><?php echo $this->getContent2P1() ?></div>
                    <?php else: ?>
                        <div class="textBox textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "><?php echo $this->getContent1P1() ?></div>
                    <?php endif; ?>
                <?php endif; ?>


                    <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_zk/".substr(strval($_i+100),1,3).".png") ?>" alt="" /></div>
                </li>

            <?php endfor; ?>

        </ul>
        <!-- 第六套 e -->

        
        <?php elseif(($this->getTypeP1() != 1 && $this->getTypeP1() != 2) && $this->getTypeP2() == 1): ?>
        <!-- 第七套 s -->
        <!-- 空-图片 -->
        <ul class="big_pic">
            <?php

            $_arrP2 = array(7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26);
            for ($_i = 1; $_i <= 32; $_i++): ?>

                <?php if($_i == 1): ?>
                    <li style="z-index:1;">
                <?php else: ?>
                    <li>
                <?php endif; ?>

                <!-- P2  -->
                <?php if(in_array($_i, $_arrP2)): ?>
                    <div class="imgBox imgPag_2 imgPag_2_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P2() ?>" alt="" /></div>
                <?php endif; ?>

                    <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_kt/".substr(strval($_i+100),1,3).".png") ?>" alt="" /></div>
                </li>

            <?php endfor; ?>
            
        </ul>



        <!-- 第七套 e -->

        
        <?php elseif(($this->getTypeP1() != 1 && $this->getTypeP1() != 2) && $this->getTypeP2() == 2): ?>
        <!-- 第八套 s -->
        <!-- 空-文字 -->
        <ul class="big_pic">
            <?php

            $_arrP2 = array(13,14,15,16,17,18,19,20,21,22,23,24,25,26);
            for ($_i = 1; $_i <= 32; $_i++): ?>

                <?php if($_i == 1): ?>
                    <li style="z-index:1;">
                <?php else: ?>
                    <li>
                <?php endif; ?>

                <!-- P2  -->
                <?php if(in_array($_i, $_arrP2)): ?>
                    <?php if($this->getContent3P2() == 4): ?>
                        <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>"><?php echo $this->getContent1P2() ?></div>
                        <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?> towLine_view_2"><?php echo $this->getContent2P2() ?></div>
                    <?php else: ?>
                        <div class="textBox textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>"><?php echo $this->getContent1P2() ?></div>
                    <?php endif; ?>
                <?php endif; ?>

                    <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_kz/".substr(strval($_i+100),1,3).".png") ?>" alt="" /></div>
                </li>

            <?php endfor; ?>
        </ul>



        <!-- 第八套 e -->
        
        
        <?php else: ?>
        <!-- 第九套 s -->
        <!-- 空-空 -->
        <ul class="big_pic">
            <?php
            $_arrP1 = array();
            $_arrP2 = array();
            for ($_i = 1; $_i <= 32; $_i++): ?>

                <?php if($_i == 1): ?>
                    <li style="z-index:1;">
                <?php else: ?>
                    <li>
                <?php endif; ?>

                    <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_kk/".substr(strval($_i+100),1,3).".png") ?>" alt="" /></div>
                </li>
            <?php endfor; ?>
        </ul>



        <!-- 第九套 e -->
        <?php endif; ?>

    </div>
</div>