<div class="cusMadeBox cusMadeCen">
    <div id="playimages" class="play" style="height:600px;">
        <div class="prev"></div>
        <div class="next"></div>

        <div class="prev_n_top"></div>
        <div class="next_z_top"></div>

        <div class="prev_n"></div>
        <div class="next_z"></div>

        <div class="viewBack viewMade"><button type="button"><img src="<?php  echo $this->getSkinUrl("images/customMade/viewMadeBack.png") ?>" alt=""></button></div>



        <?php if ($this->getTypeP1() == 1 && $this->getTypeP2() == 1): ?>
        <!-- 第一套 s -->
        <ul class="big_pic">


            <!-- 遮罩 -->
            

            <!-- 1-1 -->
            <li style="z-index:1;">
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/01.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_1"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/01.png") ?>" alt="" /></div>
            </li>

            <!-- 1-2 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/02.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_2"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/02.png") ?>" alt="" /></div>
            </li>

            <!-- 1-3 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/03.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_3"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/03.png") ?>" alt="" /></div>
            </li>

            <!-- 1-4 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/04.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_4"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/04.png") ?>" alt="" /></div>
            </li>

            <!-- 1-5 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/05.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_5"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/05.png") ?>" alt="" /></div>
            </li>

            <!-- 1-6 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/06.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_6"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/06.png") ?>" alt="" /></div>
            </li>

            <!-- 1-7 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/07.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_7"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_1"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/07.png") ?>" alt="" /></div>
            </li>

            <!-- 1-8 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/08.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_8"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_2"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/08.png") ?>" alt="" /></div>
            </li>

            <!-- 1-9 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/09.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_9"><img src="<?php  echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_3"><img src="<?php  echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/09.png") ?>" alt="" /></div>
            </li>

            <!-- 1-10 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/10.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_10"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_4"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/10.png") ?>" alt="" /></div>
            </li>

            <!-- 1-11 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/11.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_11"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_5"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/11.png") ?>" alt="" /></div>
            </li>

            <!-- 1-12 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/12.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_12"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_6"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/12.png") ?>" alt="" /></div>
            </li>

            <!-- 1-13 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/13.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_13"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_7"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/13.png") ?>" alt="" /></div>
            </li>

            <!-- 1-14 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/14.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_14"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_8"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/14.png") ?>" alt="" /></div>
            </li>

            <!-- 1-15 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/15.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_9"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/15.png") ?>" alt="" /></div>
            </li>

            <!-- 1-16 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/16.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_10"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/16.png") ?>" alt="" /></div>
            </li>

            <!-- 1-17 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/17.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_11"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/17.png") ?>" alt="" /></div>
            </li>

            <!-- 1-18 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/18.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_12"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/18.png") ?>" alt="" /></div>
            </li>

            <!-- 1-19 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/19.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_13"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/19.png") ?>" alt="" /></div>
            </li>

            <!-- 1-20 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/20.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_15"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_14"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/20.png") ?>" alt="" /></div>
            </li>

            <!-- 1-21 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/21.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_16"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_15"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/21.png") ?>" alt="" /></div>
            </li>

            <!-- 1-22 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/22.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_17"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_16"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/22.png") ?>" alt="" /></div>
            </li>

            <!-- 1-23 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/23.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_18"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_17"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/23.png") ?>" alt="" /></div>
            </li>

            <!-- 1-24 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/24.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_19"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_18"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/24.png") ?>" alt="" /></div>
            </li>

            <!-- 1-25 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/25.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_20"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_19"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/25.png") ?>" alt="" /></div>
            </li>

            <!-- 1-26 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/26.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_21"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_20"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/26.png") ?>" alt="" /></div>
            </li>

            <!-- 1-27 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/27.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_22"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_21"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/27.png") ?>" alt="" /></div>
            </li>

            <!-- 1-28 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/28.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_23"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_22"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/28.png") ?>" alt="" /></div>
            </li>

            <!-- 1-29 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/29.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_24"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_23"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/29.png") ?>" alt="" /></div>
            </li>

            <!-- 1-30 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/30.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_25"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_24"><img src="<?php echo $this->getContent2P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/30.png") ?>" alt="" /></div>
            </li>

            <!-- 1-31 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/31.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_26"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/31.png") ?>" alt="" /></div>
            </li>

            <!-- 1-32 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/32.png") ?>" alt="" /></div>
                <div class="imgBox imgPag_1 imgPag_1_27"><img src="<?php echo $this->getContent2P1() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php  echo $this->getSkinUrl("images/customMade/imgBall_y/32.png") ?>" alt="" /></div>
            </li>
        </ul>
        <!-- 第一套 e -->
        <?php elseif($this->getTypeP1() != 1 && $this->getTypeP2() != 1): ?>
        <!-- 第二套 s -->
        <ul class="big_pic">
            <!-- 遮罩 -->
            

            <!-- 2-1 -->
            <li style="z-index:1;">
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/01.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_1 "><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/01.png") ?>" alt="" /></div>
            </li>

            <!-- 2-2 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/02.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_2"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/02.png") ?>" alt="" /></div>
            </li>

            <!-- 2-3 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/03.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_3"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/03.png") ?>" alt="" /></div>
            </li>

            <!-- 2-4 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/04.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_4"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/04.png") ?>" alt="" /></div>
            </li>

            <!-- 2-5 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/05.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_5"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/05.png") ?>" alt="" /></div>
            </li>

            <!-- 2-6 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/06.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_6"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/06.png") ?>" alt="" /></div>
            </li>

            <!-- 2-7 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/07.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_7"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/07.png") ?>" alt="" /></div>
            </li>

            <!-- 2-8 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/08.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_8"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_1"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/08.png") ?>" alt="" /></div>
            </li>

            <!-- 2-9 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/09.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_9"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_2"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/09.png") ?>" alt="" /></div>
            </li>

            <!-- 2-10 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/10.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_10"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_3"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/10.png") ?>" alt="" /></div>
            </li>

            <!-- 2-11 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/11.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_11"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_4"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/11.png") ?>" alt="" /></div>
            </li>

            <!-- 2-12 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/12.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_12"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_5"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/12.png") ?>" alt="" /></div>
            </li>

            <!-- 2-13 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/13.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_13"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_6"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/13.png") ?>" alt="" /></div>
            </li>

            <!-- 2-14 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/14.png") ?>" alt="" /></div>
                <div class="textBox textPag_2 textPag_2_7"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/14.png") ?>" alt="" /></div>
            </li>

            <!-- 2-15 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/15.png") ?>" alt="" /></div>
                <div class="textBox textPag_2 textPag_2_8"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/15.png") ?>" alt="" /></div>
            </li>

            <!-- 2-16 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/16.png") ?>" alt="" /></div>
                <div class="textBox textPag_2 textPag_2_9"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/16.png") ?>" alt="" /></div>
            </li>

            <!-- 2-17 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/17.png") ?>" alt="" /></div>
                <div class="textBox textPag_2 textPag_2_10"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/17.png") ?>" alt="" /></div>
            </li>

            <!-- 2-18 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/18.png") ?>" alt="" /></div>
                <div class="textBox textPag_2 textPag_2_11"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/18.png") ?>" alt="" /></div>
            </li>

            <!-- 2-19 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/19.png") ?>" alt="" /></div>
                <div class="textBox textPag_2 textPag_2_12"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/19.png") ?>" alt="" /></div>
            </li>

            <!-- 2-20 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/20.png") ?>" alt="" /></div>
                <div class="textBox textPag_2 textPag_2_13"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/20.png") ?>" alt="" /></div>
            </li>

            <!-- 2-21 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/21.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_14"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_14"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/21.png") ?>" alt="" /></div>
            </li>

            <!-- 2-22 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/22.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_15"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_15"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/22.png") ?>" alt="" /></div>
            </li>

            <!-- 2-23 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/23.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_16"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_16"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/23.png") ?>" alt="" /></div>
            </li>

            <!-- 2-24 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/24.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_17"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_17"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/24.png") ?>" alt="" /></div>
            </li>

            <!-- 2-25 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/25.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_18"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_18"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/25.png") ?>" alt="" /></div>
            </li>

            <!-- 2-26 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/26.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_19"><?php echo $this->getContent1P1() ?></div>
                <div class="textBox textPag_2 textPag_2_19"><?php echo $this->getContent1P2() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/26.png") ?>" alt="" /></div>
            </li>

            <!-- 2-27 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/27.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_20"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/27.png") ?>" alt="" /></div>
            </li>

            <!-- 2-28 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/28.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_21"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/28.png") ?>" alt="" /></div>
            </li>

            <!-- 2-29 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/29.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_22"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/29.png") ?>" alt="" /></div>
            </li>

            <!-- 2-30 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/30.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_23"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/30.png") ?>" alt="" /></div>
            </li>

            <!-- 2-31 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/31.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_24"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/31.png") ?>" alt="" /></div>
            </li>

            <!-- 2-32 -->
            <li>
                <div class="zz"><img src="<?php echo $this->getSkinUrl("images/customMade/zz/32.png") ?>" alt="" /></div>
                <div class="textBox textPag_1 textPag_1_25"><?php echo $this->getContent1P1() ?></div>
                <div class="imgBox imgBall"><img src="<?php echo $this->getSkinUrl("images/customMade/imgBall_n/32.png") ?>" alt="" /></div>
            </li>

        </ul>

        <?php elseif($this->getTypeP1() == 1 && $this->getTypeP2() != 1): ?>
        <!-- 第三套 s -->





        <!-- 第三套 e -->
        <?php else: ?>
        <!-- 第四套 s -->





        <!-- 第四套 e -->
        <?php endif; ?>

    </div>
</div>

<script type="text/javascript">

    jQuery(function () {

        <?php if ($this->getContent2P1() == '3'): ?>
            jQuery(".textPag_1").addClass("size_80");
        <?php elseif($this->getContent2P1() == '2'): ?>
            jQuery(".textPag_1").addClass("size_60");
        <?php else: ?>
            jQuery(".textPag_1").addClass("size_40");
        <?php endif; ?>

        <?php if ($this->getContent2P2() == '3'): ?>
        jQuery(".textPag_2").addClass("size_80");
        <?php elseif($this->getContent2P2() == '2'): ?>
        jQuery(".textPag_2").addClass("size_60");
        <?php else: ?>
        jQuery(".textPag_2").addClass("size_40");
        <?php endif; ?>
    });

</script>