<?php
$orderId = (int)Mage::getSingleton('core/session')->getOrderId();
if(!$orderId){
    echo '订单错误，请联系我们.商城客服电话：18017018167';
    exit();
}
$_order = Mage::getModel('sales/order')->load($orderId);

$realOrderId = $_order->getIncrementId();
if (!$_order->getId()) {
    echo '订单错误，请联系我们.商城客服电话：18017018167';
    exit();
}
if ($_order->getStatus() == "alipay_wait_seller_send_goods") {
    echo "亲 " .$realOrderId . " 已付款成功！";
    return;
}
//使用jsapi接口
//$jsApi = new JsApi_pub();
$jsApi = Mage::getModel('weixinpay/jsapipub');
//=========步骤1：网页授权获取用户openid============
//通过code获得openid
if (!isset($_GET['code']))
{
    //触发微信返回code码
    $currentUrl = $this->helper('core/url')->getCurrentUrl();
    $url = $jsApi->createOauthUrlForCode($currentUrl);
    Header("Location: $url");
}else
{
    //获取code码，以获取openid
    $code = $_GET['code'];
    $jsApi->setCode($code);
    $openid = $jsApi->getOpenId();
}
//=========步骤2：使用统一支付接口，获取prepay_id============
//使用统一支付接口
$unifiedOrder = Mage::getModel('weixinpay/unifiedorderpub');

//设置统一支付接口参数
//设置必填参数
//appid已填,商户无需重复填写
//mch_id已填,商户无需重复填写
//noncestr已填,商户无需重复填写
//spbill_create_ip已填,商户无需重复填写
//sign已填,商户无需重复填写
$shopName = Infinitech_Weixinpay_Model_Wxpaypubconfig::getCode("shop_name");

$unifiedOrder->setParameter("openid","$openid");//商品描述
$unifiedOrder->setParameter("body","$shopName");//商品描述
//自定义订单号，此处仅作举例
$timeStamp = time();
//$out_trade_no = Infinitech_Weixinpay_Model_Wxpaypubconfig::getCode("app_id")."$timeStamp";
$out_trade_no = $realOrderId."$timeStamp";
$unifiedOrder->setParameter("out_trade_no","$realOrderId");//商户订单号

$totalFee = $_order->getGrandTotal() * 100;
$unifiedOrder->setParameter("total_fee","$totalFee");//总金额
$unifiedOrder->setParameter("notify_url",$unifiedOrder->getNotifyUrl());//通知地址
$unifiedOrder->setParameter("trade_type","JSAPI");//交易类型
//非必填参数，商户可根据实际情况选填
//$unifiedOrder->setParameter("sub_mch_id","XXXX");//子商户号
//$unifiedOrder->setParameter("device_info","XXXX");//设备号
//$unifiedOrder->setParameter("attach","XXXX");//附加数据
//$unifiedOrder->setParameter("time_start","XXXX");//交易起始时间
//$unifiedOrder->setParameter("time_expire","XXXX");//交易结束时间
//$unifiedOrder->setParameter("goods_tag","XXXX");//商品标记
//$unifiedOrder->setParameter("openid","XXXX");//用户标识
//$unifiedOrder->setParameter("product_id","XXXX");//商品ID

$prepay_id = $unifiedOrder->getPrepayId();
//=========步骤3：使用jsapi调起支付============
$jsApi->setPrepayId($prepay_id);

$jsApiParameters = $jsApi->getParameters();
?>

<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <title>微信安全支付</title>
    <script type="text/javascript">

        //调用微信JS api 支付
        function jsApiCall()
        {
            WeixinJSBridge.invoke(
                'getBrandWCPayRequest',
                <?php echo $jsApiParameters; ?>,
                function(res){
                    WeixinJSBridge.log(res.err_msg);
                  //  alert(res.err_code+res.err_desc+res.err_msg);
                }
            );
        }

        function callpay()
        {
            if (typeof WeixinJSBridge == "undefined"){
                if( document.addEventListener ){
                    document.addEventListener('WeixinJSBridgeReady', jsApiCall, false);
                }else if (document.attachEvent){
                    document.attachEvent('WeixinJSBridgeReady', jsApiCall);
                    document.attachEvent('onWeixinJSBridgeReady', jsApiCall);
                }
            }else{
                jsApiCall();
            }
        }
        var i = 0;
        jQuery(document).ready(function(){
            callpay();

            window.code = 400;
            var qrcodeChangeInternal = setInterval(changeQrcode, 1 * 1000);

            function changeQrcode() {
                i++;
                if(i<3600){
                    jQuery.getScript('<?php echo $this->getUrl('weixinpay/payment/js',array('order_id'=>$_order->getId()));?>');
                    switch (window.code) {
                        case 400:
                        case 408:
                            break;
                        case 300:
                            //付款成功，需要显示付款成功的标签
                            jQuery(".msg_box").show();
                            jQuery("#paybutton").hide();
                            clearInterval(qrcodeChangeInternal);
                            break;
                    }
                }else{
                    clearInterval(qrcodeChangeInternal);
                }

            }
        });

    </script>
</head>
<body>
</br></br></br></br>
<div align="center">
    <button id="paybutton" style="width:210px; height:30px; background-color:#FE6714; border:0px #FE6714 solid; cursor: pointer;  color:white;  font-size:16px;" type="button" onclick="callpay()" >点击付款</button>
</div>
<div align="center" class="msg_box" style="display: none;">
    <i class="icon60_qr pngFix"></i>

    <p><strong>付款成功</strong><br/><a href="<?php echo $this->getUrl('sales/order/view',array('order_id'=>$_order->getId())); ?>">查看订单</a></p>
</div>
</body>
</html>