<?php
/**
 * Requires creating of cms page and setting for mobile view.
 * setTemplate = "page/home.phtml"
 * add layoutXML head/refs for skin_js/index.js and skin_css/index.css
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
	<?php echo $this->getChildHtml('head') ?>

<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/jquery.iosslider.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/swipe.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/jquery.SuperSlide.2.1.1.js"></script>
<script>
	jQuery(function(){
		new Swipe(document.getElementById('banner_box'), {
			speed:500,
			auto:3000,
			callback: function(){
				var lis = jQuery(this.element).next("ol").children();
				lis.removeClass("on").eq(this.index).addClass("on");
			}
		});
		new Swipe(document.getElementById('news_box'), {
			speed:500,
			auto:3000,
			callback: function(){
				var lis = jQuery(this.element).next("ol").children();
				lis.removeClass("on").eq(this.index).addClass("on");
			}
		});
		// back to top eff
		jQuery('.e-back-top').click(function(){
			jQuery("html, body").animate({ scrollTop: 0 }, 300);
		})
	});

</script>
</head>
<!--Ω-->
<body>
<div id="page" class="ui-whole-page e-whole-page">
	<div class="ui-page e-page">

	<?php echo $this->getChildHtml('after_body_start') ?>
	<?php echo $this->getChildHtml('global_notices') ?>
	<?php echo $this->getChildHtml('header') ?>



	<div class="home-wrapper">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mobile_home_page_sections')->toHtml(); ?>

		<?php

		$_category = Mage::getModel('catalog/category')->load(573);
		$_productCollection = Mage::getResourceModel('catalog/product_collection')
			->addCategoryFilter($_category)
			->addAttributeToSelect('*')
			->addAttributeToFilter('status', 1)
			->addAttributeToFilter('visibility', 4);
		$_helper = $this->helper('catalog/output');
		?>

		<!-- 包邮 -->
		<div class="by">
			<span><img src="<?php echo $this->getSkinUrl('images/by.png');?>" border="0"></span>
			<span>全场满228名邮费</span>
		</div>
        <div class="checktf" style="-webkit-transform:translate3d(0,0,0);">
			<div id="banner_box" class="box_swipe">
				<ul>
<!--					<li><a href="--><?php //echo Mage::getUrl('65-621-65621y.html'); ?><!--"><img src="--><?php //echo Mage::getModel('core/variable')->loadByCode('aliyun_mobile_image')->getValue('html'); ?><!--images/banIndex01.jpg"></a></li>-->
					<li><a href="<?php echo Mage::getUrl('65-621-65621y.html'); ?>"><img src="<?php echo $this->getSkinUrl('images/banana-2016-1.jpg');?>" border="0"></a></li>
					<li><a href="<?php echo Mage::getUrl('65-621-65621y.html'); ?>"><img src="<?php echo $this->getSkinUrl('images/banana-2016-2.jpg');?>" border="0"></a></li>
<!--					<li><a href="--><?php //echo Mage::getUrl('store/index/confirm'); ?><!--"><img src="--><?php //echo Mage::getModel('core/variable')->loadByCode('aliyun_mobile_image')->getValue('html'); ?><!--images/verify.jpg"></a></li>-->
				</ul>
				<ol>
					<li class="on"></li>
					<li class=""></li>
				</ol>
			</div>
        </div>
	<!-- main category entrance banner -->
	<!--<section class="banner-main-wrapper clearfix" style>
		<div class="banner-sub">
			<div class="banner-sub-img">
				<a href="<?php /*echo Mage::getUrl(''); */?>products/baseketball-series.html?attribute_set_name=72"><img src="<?php /*echo Mage::getModel('core/variable')->loadByCode('aliyun_mobile_image')->getValue('html'); */?>images/home_ball.jpg"></a>
			</div>
		</div>

		<div class="banner-sub">
			<div class="banner-sub-img">
				<a href="<?php /*echo Mage::getUrl(''); */?>catalogsearch/result/?q=包"><img src="<?php /*echo Mage::getModel('core/variable')->loadByCode('aliyun_mobile_image')->getValue('html'); */?>images/home_bag.jpg"></a>
			</div>
		</div>
	</section>
	<section class="banner-main-wrapper clearfix">
		<div class="banner-sub">
			<div class="banner-sub-img">
				<a href="<?php /*echo Mage::getUrl(''); */?>catalogsearch/result/?q=背心%20裤%20针织%20短袖"><img src="<?php /*echo Mage::getModel('core/variable')->loadByCode('aliyun_mobile_image')->getValue('html'); */?>images/home_apparel.jpg"></a>
			</div>
		</div>

		<div class="banner-sub">
			<div class="banner-sub-img">
				<a href="<?php /*echo Mage::getUrl(''); */?>products/accessories.html"><img src="<?php /*echo Mage::getModel('core/variable')->loadByCode('aliyun_mobile_image')->getValue('html'); */?>images/home_onesize.jpg"></a>
			</div>
		</div>
	</section>-->
	<section class="section-wraper-16 clearfix">
		<div class="section-16-box ms-fl">
			<a href="#">
				<img src="<?php echo $this->getSkinUrl('images/section-2016-1.png');?>" border="0">
			</a>
		</div>
		<div class="section-16-box ms-fr">
			<a href="#">
				<img src="<?php echo $this->getSkinUrl('images/section-2016-2.png');?>" border="0">
			</a>
		</div>
	</section>
	<!-- main category entrance banner -->

	<div class="menu-kinds">
		<div class="menu-kinds-box clearfix">
			<a href="#">
				<img src="<?php echo $this->getSkinUrl('images/menu-kinds-1.png');?>" border="0">
			</a>
			<a href="#">
				<img src="<?php echo $this->getSkinUrl('images/menu-kinds-2.png');?>" border="0">
			</a>
		</div>
		<div class="menu-kinds-box clearfix">
			<a href="#">
				<img src="<?php echo $this->getSkinUrl('images/menu-kinds-3.png');?>" border="0">
			</a>
			<a href="#">
				<img src="<?php echo $this->getSkinUrl('images/menu-kinds-4.png');?>" border="0">
			</a>
		</div>
		<div class="menu-kinds-box clearfix">
			<a href="#">
				<img src="<?php echo $this->getSkinUrl('images/menu-kinds-5.png');?>" border="0">
			</a>
			<a href="#">
				<img src="<?php echo $this->getSkinUrl('images/menu-kinds-6.png');?>" border="0">
			</a>
		</div>
	</div>

	<!-- 推荐商品 -->
		<div class="prosTit">
			<h2>推荐商品</h2>
		</div>
		<div class="picScroll-left">
			<div class="hd">
				<a class="next"></a>
				<a class="prev"></a>
			</div>
			<div class="bd">
				<ul class="picList">
					<li>
						<div class="pic"><a href="" target="_blank"><img src="<?php echo $this->getSkinUrl('images/product-temp.png');?>" border="0"></a></div>
						<div class="title">
							<h3>NBA经典"掌控"室内室外篮球</h3>
							<p><span class="price-emp">$229.00</span><span class="price-now">$183.00</span></p>
						</div>
					</li>
					<li>
						<div class="pic"><a href="" target="_blank"><img src="<?php echo $this->getSkinUrl('images/product-temp.png');?>" border="0"></a></div>
						<div class="title">
							<h3>NBA经典"掌控"室内室外篮球</h3>
							<p><span class="price-emp">$229.00</span><span class="price-now">$183.00</span></p>
						</div>
					</li>
					<li>
						<div class="pic"><a href="" target="_blank"><img src="<?php echo $this->getSkinUrl('images/product-temp.png');?>" border="0"></a></div>
						<div class="title">
							<h3>NBA经典"掌控"室内室外篮球</h3>
							<p><span class="price-emp">$229.00</span><span class="price-now">$183.00</span></p>
						</div>
					</li>
					<li>
						<div class="pic"><a href="" target="_blank"><img src="<?php echo $this->getSkinUrl('images/product-temp.png');?>" border="0"></a></div>
						<div class="title">
							<h3>NBA经典"掌控"室内室外篮球</h3>
							<p><span class="price-emp">$229.00</span><span class="price-now">$183.00</span></p>
						</div>
					</li>
					<li>
						<div class="pic"><a href="" target="_blank"><img src="<?php echo $this->getSkinUrl('images/product-temp.png');?>" border="0"></a></div>
						<div class="title">
							<h3>NBA经典"掌控"室内室外篮球</h3>
							<p><span class="price-emp">$229.00</span><span class="price-now">$183.00</span></p>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<script type="text/javascript">
			jQuery(".picScroll-left").slide({titCell:".hd ul",mainCell:".bd ul",autoPage:true,effect:"left",autoPlay:false,vis:2,trigger:"click"});
		</script>

		<!-- 新闻 -->
	<div class="checktf" style="-webkit-transform:translate3d(0,0,0);">
		<div id="news_box" class="box_swipe news-swipe">
			<ul>
				<li>
					<img src="<?php echo $this->getSkinUrl('images/news-box-img-1.png');?>" border="0">
					<div class="news-swipe-box">
						<h3>2016-03-26</h3>
						<h2>SPALDING NBA全明星赛系列篮球亮相多伦多!</h2>
						<p>北京时间2月12日，2015-2016NBA赛季全明星周末在加拿大多伦多拉开了序幕。作为全球顶级的篮球装备供应商之一、世界篮球品牌斯伯丁，为本届NBA全明星赛事专属打造的官方比赛系列篮球正式在赛场上公布亮相。</p>
						<a href="#">了解更多</a>
					</div>
				</li>
			</ul>
		</div>
	</div>

	<!-- 返回顶部 -->
	<div class="e-back-top">
		<img src="<?php echo $this->getSkinUrl('images/to-top.jpg');?>" border="0">
	</div>

		<div class="clearfloats"></div>
		<!-- 底部 -->
		<?php echo $this->getChildHtml('footer') ?>
	</div>
	</div>
</div>

<script type="text/javascript">

	jQuery('.iosSliderStyles').iosSlider({
		startAtSlide: 1,
		snapToChildren: true,
		snapSlideCenter: false,
		snapVelocityThreshold: 0,
		desktopClickDrag: true,
		infiniteSlider: false,
		navPrevSelector: 'a.sliderMiniPrev',
		navNextSelector: 'a.sliderMiniNext',
		keyboardControls: false
	});

	// Allowing it to be visible when drawing causes all four slides to be visible momentarily.
	// 'display: none' would cause the page jump. This method maintains the placeholder position.
	jQuery('.iosSliderStyles').css({'opacity': '1', 'filter': 'alpha(opacity:100)'});

</script>

<!-- BEGIN: Google Trusted Stores -->
<script type="text/javascript">
//  var gts = gts || [];
//
//  gts.push(["id", "66454"]);
//  //gts.push(["google_base_offer_id", "ITEM_GOOGLE_SHOPPING_ID"]);
//  gts.push(["google_base_subaccount_id", "57460"]);
//  gts.push(["google_base_country", "US"]);
//  gts.push(["google_base_language", "EN"]);
//
//  (function() {
//	var scheme = (("https:" == document.location.protocol) ? "https://" : "http://");
//	var gts = document.createElement("script");
//	gts.type = "text/javascript";
//	gts.async = true;
//	gts.src = scheme + "www.googlecommerce.com/trustedstores/gtmp_compiled.js";
//	var s = document.getElementsByTagName("script")[0];
//	s.parentNode.insertBefore(gts, s);
//  })();
</script>
<!-- END: Google Trusted Stores -->

</body>
</html>