<?php
/**
 * Requires creating of cms page and setting for mobile view.
 * setTemplate = "page/home.phtml"
 * add layoutXML head/refs for skin_js/index.js and skin_css/index.css
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>

    <script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/jquery.iosslider.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/swipe.js"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/jquery.SuperSlide.2.1.1.js"></script>
    <script>
        jQuery(function () {
            new Swipe(document.getElementById('banner_box'), {
                speed: 500,
                auto: 3000,
                callback: function () {
                    var lis = jQuery(this.element).next("ol").children();
                    lis.removeClass("on").eq(this.index).addClass("on");
                }
            });
            new Swipe(document.getElementById('news_box'), {
                speed: 500,
                auto: 3000,
                callback: function () {
                    var lis = jQuery(this.element).next("ol").children();
                    lis.removeClass("on").eq(this.index).addClass("on");
                }
            });
            // back to top eff
            jQuery('.e-back-top').click(function () {
                jQuery("html, body").animate({scrollTop: 0}, 300);
            })
        });

    </script>
</head>
<!--Ω-->
<body>
<div id="page" class="ui-whole-page e-whole-page">
    <div class="ui-page e-page">

        <?php echo $this->getChildHtml('after_body_start') ?>
        <?php echo $this->getChildHtml('global_notices') ?>
        <?php echo $this->getChildHtml('header') ?>


        <div class="home-wrapper">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('free_shipping')->toHtml() ?>
            <div class="hd"></div>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mobile_home_banner')->toHtml() ?>
            <!-- 推荐商品 -->
            <div class="prosTit">
                <h2>推荐商品</h2>
            </div>
            <div class="picScroll-left">
                <div class="hd">
                    <a class="next"></a>
                    <a class="prev"></a>
                </div>
                <div class="bd">
                    <ul class="picList">
                        <?php
                        $category = Mage::getModel('catalog/category')->loadByAttribute('url_key', 'recommend');
                        $collection = $category->getProductCollection();
                        $index = 0;
                        foreach ($collection as $_productT):
                        $index++;
                        if ($index > 12) {
                        break;
                        }
                        $_product = Mage::getModel('catalog/product')->load($_productT->getId());
                        $_productNameStripped = $this->stripTags($_product->getName(), null, true);
                        ?>
                        <li>
                            <div class="pic">
                                <a href="<?php echo $_product->getProductUrl() ?>">
                                    <img
                                            src="<?php echo Mage::getModel('core/variable')->loadByCode('static_image_domain')->getValue('html') .'/is/image/sneakerhead/cat-single?$185m$&$img=sneakerhead/'. $_product->getUrlKey() ."-1"  ?>"
                                    alt="<?php echo $_productNameStripped; ?>">
                                </a>
                            </div>
                            <div class="title">
                                <h3><?php echo $_product->getName() ?></h3>

                                <p>
                                    <?php
                                        $msrp = number_format($_product->getMsrp(), '2', '.', ',');
                                    $currentPrice = number_format($_product->getPrice(), '2', '.', ',');
                                    if ($msrp != $currentPrice):
                                    ?>
                                    <span class="price-emp">
									￥<?php echo $msrp; ?>
								</span>
                                    <?php
                                        endif;
                                        ?>
                                    <span class="price-now">￥<?php echo $currentPrice; ?></span>
                                </p>
                            </div>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
            <script type="text/javascript">
                jQuery(".picScroll-left").slide({
                    titCell: ".hd ul",
                    mainCell: ".bd ul",
                    autoPage: true,
                    effect: "left",
                    autoPlay: false,
                    vis: 2,
                    trigger: "click"
                });
            </script>


            <div class="series-product-box">
                <div class="big">
                    <!-- 定制 -->
                    <a href="<?php echo Mage::getUrl(''); ?>custom-made.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home1.jpg'); ?>" border="0">
                    </a>

                    <!-- 系列 -->
                    <a href="<?php echo Mage::getUrl(''); ?>products/basketball/series/nba-game.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home2.jpg'); ?>" border="0">
                    </a>
                </div>
            </div>

            <!-- 专用篮球 -->
            <div class="series-product-box">
                <div class="double-product clearfix">
                    <a href="<?php echo Mage::getUrl(''); ?>products/basketball/place/indoor.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home3.jpg'); ?>" border="0">
                    </a>
                    <a href="<?php echo Mage::getUrl(''); ?>products/basketball/place/outdoor.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home4.jpg'); ?>" border="0">
                    </a>
                </div>

                <div class="big">
                    <a href="<?php echo Mage::getUrl(''); ?>products/basketball/place/inoutdoor.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home5.jpg'); ?>" border="0">
                    </a>
                </div>
            </div>

            <!-- 空隙白条 -->
            <div class="margin">
                <img src="<?php echo $this->getSkinUrl('images/home/margin.jpg'); ?>" border="0" style="width: 100%;">
            </div>

            <!-- main category entrance banner -->

            <div class="menu-kinds" style="margin: 0">
                <div class="menu-kinds-box clearfix">
                    <a href="<?php echo Mage::getUrl('products/basketball.html'); ?>">
                        <img src="<?php echo $this->getSkinUrl('images2019/home6.jpg'); ?>" border="0">
                    </a>
                    <a href="<?php echo Mage::getUrl(''); ?>products/accessories.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home7.jpg'); ?>" border="0">
                    </a>
                </div>
                <div class="menu-kinds-box clearfix">
                    <a href="<?php echo Mage::getUrl(''); ?>products/stands.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home8.jpg'); ?>" border="0">
                    </a>
                    <a href="<?php echo Mage::getUrl(''); ?>products/apparel.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home9.jpg'); ?>" border="0">
                    </a>
                </div>
                <div class="menu-kinds-box clearfix">
                    <a href="<?php echo Mage::getUrl(''); ?>products/trainingseries.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home10.jpg'); ?>" border="0">
                    </a>
                    <a href="<?php echo Mage::getUrl(''); ?>products/football.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home11.jpg'); ?>" border="0">
                    </a>
                </div>
                <div class="menu-kinds-box clearfix">
                    <a href="<?php echo Mage::getUrl(''); ?>newproduct.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home12.jpg'); ?>" border="0">
                    </a>
                    <a href="<?php echo Mage::getUrl(''); ?>products.html">
                        <img src="<?php echo $this->getSkinUrl('images2019/home13.jpg'); ?>" border="0">
                    </a>
                </div>
            </div>

            <!-- 空隙白条 -->
            <div class="margin">
                <img src="<?php echo $this->getSkinUrl('images/home/margin.jpg'); ?>" border="0" style="width: 100%;">
            </div>

            <!-- 视频 -->
            <video class="media Jvideo1" id="Jvideo1" controls poster="<?php echo $this->getSkinUrl('images/home/tv.jpg'); ?>" width="100%">
                <source src="http://images.spalding.com.cn/images/home/mobile/index.mp4" type="video/mp4">
                Your browser does not support the video tag.
            </video>

            <!--品牌故事 防伪验证-->
            <section class="section-wraper-16 clearfix" style="margin: 0;">
                <div class="section-16-box percent50 ms-fl">
                    <a href="<?php echo Mage::getUrl('sm_20180731') ?>">
                        <img src="<?php echo $this->getSkinUrl('images2019/home14.jpg') ?>" border="0">
                    </a>
                </div>
                <div class="section-16-box percent50 ms-fr">
                    <a href="
                    <?php echo Mage::getUrl('store/index/confirm'); ?>">
                        <img src="<?php echo $this->getSkinUrl('images2019/home15.jpg') ?>" border="0">
                    </a>
                </div>
            </section>

            <!-- 新闻 -->
            <div id="news_box" class="box_swipe news-swipe">
                <ul>
                    <?php
                    $blogPosts = Mage::getModel('blog/blog')->getCollection()
                    ->setOrder('created_time', 'desc')
                    ->setPageSize(3);
                    foreach ($blogPosts as $post) {
                    echo $post->getMobileShortContent();
                    }
                    ?>
                </ul>
            </div>

            <!-- 返回顶部 -->
            <div class="e-back-top">
                <img src="<?php echo $this->getSkinUrl('images2019/back-top.jpg'); ?>" border="0">
            </div>

            <div class="clearfloats"></div>
            <!-- 底部 -->
            <?php echo $this->getChildHtml('footer') ?>
        </div>
    </div>
</div>

<script type="text/javascript">

    jQuery('.iosSliderStyles').iosSlider({
        startAtSlide: 1,
        snapToChildren: true,
        snapSlideCenter: false,
        snapVelocityThreshold: 0,
        desktopClickDrag: true,
        infiniteSlider: false,
        navPrevSelector: 'a.sliderMiniPrev',
        navNextSelector: 'a.sliderMiniNext',
        keyboardControls: false
    });

    // Allowing it to be visible when drawing causes all four slides to be visible momentarily.
    // 'display: none' would cause the page jump. This method maintains the placeholder position.
    jQuery('.iosSliderStyles').css({'opacity': '1', 'filter': 'alpha(opacity:100)'});

</script>

<!-- BEGIN: Google Trusted Stores -->
<script type="text/javascript">
    //  var gts = gts || [];
    //
    //  gts.push(["id", "66454"]);
    //  //gts.push(["google_base_offer_id", "ITEM_GOOGLE_SHOPPING_ID"]);
    //  gts.push(["google_base_subaccount_id", "57460"]);
    //  gts.push(["google_base_country", "US"]);
    //  gts.push(["google_base_language", "EN"]);
    //
    //  (function() {
    //	var scheme = (("https:" == document.location.protocol) ? "https://" : "http://");
    //	var gts = document.createElement("script");
    //	gts.type = "text/javascript";
    //	gts.async = true;
    //	gts.src = scheme + "www.googlecommerce.com/trustedstores/gtmp_compiled.js";
    //	var s = document.getElementsByTagName("script")[0];
    //	s.parentNode.insertBefore(gts, s);
    //  })();
</script>
<!-- END: Google Trusted Stores -->

</body>
</html>