<?php $_product = $this->getProduct(); ?>
<?php $_taxHelper = $this->helper('tax'); ?>



<?php echo $this->getChildHtml('custommade_view_options_custom') ?>

<!-- 右侧设置通栏 s -->
<div class="cusMadeBox cusMadeRig">
    <div class="madeBoxVal">
        <h1>SPALDING 74-604 ID</h1>
        <h2>价格：￥<?php echo $_taxHelper->getPrice($_product, $this->getPrice())?></h2>
    </div>
    <div class="madeP_btn madeP_1_btn madeP_btn_now">P1</div>
    <div class="madeP_btn madeP_2_btn">P2</div>

    <!-- p1 -->
    <div class="madeBoxCons madeBoxCons_p1">
        <h3>可定制球皮</h3>
        <p class="madeTs">选择添加图案或个性签名</p>
        <p class="madeSn">（每块定制球皮只可选择以下一种定制）</p>
        <!-- 定制参数 -->
        <dl class="madeBoxFuns">
            <dd class="madeKindTit madeKindTitImg" dataVal='1'>定制图案</dd>
            <dd class="zz"></dd>
            <dt class="madeKindCons madeKindImg" style="display: none">
                <h5>***注意***</h5>
                <p>支持jpg、gif、png格式，单张图片大小2M-8M</p>
            </dt>

            <dd class="madeKindTit madeKindTitTex" dataVal='2'>定制文字</dd>
            <dd class="zz"></dd>
            <dt class="madeKindCons madeKindTex">
                <div class="madeTextInp clearfix">
                    <input type="text" class="madeTextInpBox" placeholder="请输入定制文字" id="textInput_1" onkeyup="SwapTxt_1()">
                </div>
                <p>请选择字号：</p>
                <div id="customMade_fontSize_1" class="madeKindTexSpan">
                    <div class="sale-num">
                        <input type="radio" class="required-entry super-attribute-select" id="attribute2098" name="aa" data-input="kinds" value="53">
                        <span class="size_kind setSize_80" for="attribute2098" name="attribute2098">大号字体</span>
                        <input type="radio" class="required-entry super-attribute-select" id="attribute2097" name="aa" data-input="kinds" value="54" checked="checked">
                        <span class="size_kind setSize_60 checked" for="attribute2097" name="attribute2097">中号字体</span>
                        <input type="radio" class="required-entry super-attribute-select" id="attribute2096" name="aa" data-input="kinds" value="55">
                        <span class="size_kind setSize_40" for="attribute2096" name="attribute2096">小号字体</span>
                    </div>
                </div>
            </dt>
            <dt class="zz_t"></dt>
            <dd class="madeKindTit madeKindTitNon madeNow"  dataVal='3'>空白</dd>
            <dd class="zz"></dd>
        </dl>

        <div class="madeSubmit">
            <button type="button" class="submitY">完成P1定制</button>
            <button type="button" class="submitN">重置此次定制</button>
        </div>

        <!-- 确认&放弃提示 P1 -->
        <div class="comfBox comfBox_1">
            <p>是否保存当前定制？</p>
            <div class="confBtn">
                <button type="button" class="saveMadeY saveMadeY_p1">是</button>
                <button type="button" class="saveMadeN saveMadeN_p1">否</button>
            </div>
        </div>
    </div>

    <!-- p2 -->
    <div class="madeBoxCons madeBoxCons_p2" style="display:none;">
        <h3>可定制球皮</h3>
        <p class="madeTs">选择添加图案或个性签名</p>
        <p class="madeSn">（每块定制球皮只可选择以下一种定制）</p>
        <!-- 定制参数 -->
        <dl class="madeBoxFuns">
            <dd class="madeKindTit madeKindTitImg" dataVal='1'>定制图案</dd>
            <dd class="zz"></dd>
            <dt class="madeKindCons madeKindImg" style="display: none">
            <h5>***注意***</h5>
            <p>支持jpg、gif、png格式，单张图片大小2M-8M</p>
            </dt>
            <dd class="madeKindTit madeKindTitTex" dataVal='2'>定制文字</dd>
            <dd class="zz"></dd>
            <dt class="madeKindCons madeKindTex">
            <div class="madeTextInp clearfix">
                <input type="text" class="madeTextInpBox" placeholder="请输入定制文字" id="textInput_2" onkeyup="SwapTxt_2()">
            </div>
            <div id="customMade_fontSize_2" class="madeKindTexSpan">
                <div class="sale-num">
                    <input type="radio" class="required-entry super-attribute-select" id="attribute2093" name="bb" data-input="kinds" value="53">
                    <span class="size_kind setSize_80" for="attribute2093" name="attribute2093">大号字体</span>
                    <input type="radio" class="required-entry super-attribute-select" id="attribute2092" name="bb" data-input="kinds" value="54">
                    <span class="size_kind setSize_60 checked" for="attribute2092" name="attribute2092">中号字体</span>
                    <input type="radio" class="required-entry super-attribute-select" id="attribute2091" name="bb" data-input="kinds" value="55">
                    <span class="size_kind setSize_40" for="attribute2091" name="attribute2091">小号字体</span>
                </div>
            </div>

            </dt>
            <dt class="zz_t"></dt>
            <dd class="madeKindTit madeKindTitNon madeNow" dataVal='3'>空白</dd>
            <dd class="zz"></dd>
        </dl>

        <div class="madeSubmit">
            <button type="button" class="submitY">完成P2定制</button>
            <button type="button" class="submitN">重置此次定制</button>
        </div>

        <!-- 确认&放弃提示 P1 -->
        <div class="comfBox comfBox_2">
            <p>是否保存当前定制？</p>
            <div class="confBtn">
                <button type="button" class="saveMadeY saveMadeY_p2">是</button>
                <button type="button" class="saveMadeN saveMadeN_p2">否</button>
            </div>
        </div>
    </div>

    <div style="display:none;">
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
        <input type="hidden" name="related_product" id="related-products-field" value=""/>
        <input type="hidden" name="super_attribute[2094]" value="<?php echo $this->getSize() ?>"/>
        <input type="hidden" name="super_attribute[2112]" value="<?php echo $this->getCustomType() ?>"/>
    </div>

    <div class="madeFuns">
        <button type="submit" onclick="productAddToCartForm.submit(this)">加入购物车</button>
    </div>
</div>
<!-- 右侧设置通栏 e -->



<!-- 编辑后单面预览 P1 -->
<div class="viewPage_P1" dataType="2">
    <div class="viewPage_P1_bg">
        <img class="pageBg" src="" alt="">
    </div>
    <div class="viewPage_p1_wrap">
        
    </div>
</div>
<!-- 编辑后单面预览 P2 -->
<div class="viewPage_P2" dataType="2">
    <div class="viewPage_P2_bg">
        <img class="pageBg" src="" alt="">
    </div>
    <div class="viewPage_p2_wrap">
        
    </div>
</div>
