<!--
<div class="comment-block">
<h3><?php echo $this->__('Comment')?></h3>
    <div  class="collapse-block hidden">
	<form autocomplete="off">
	    <div class="comment">
	        <div class="comment-form">            
	            <div class="input-box">	                
	                <textarea class="input-text" id="customer_comment" name="customer_comment"></textarea>
	            </div>	            
	        </div>
	    </div>
	</form>
	</div>
</div>
-->
<div class="checkoutLine"></div>

<div class="checkoutSubTitleMain">
    <span class="checkoutSubTitleBall">
        <img src="<?php echo $this->getSkinUrl('images/add_comment.png');  ?>" alt="">
    </span>
</div>

<div class="checkoutSmallTitle">
    添加备注：（对订单的要求或特别注明）
    <textarea class="input-text checkoutCommentText" id="customer_comment" name="customer_comment"></textarea>
    <input type="hidden" name="customer_invoice" id="customer_invoice">
</div>
