<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<p class="left" style="display:none"><a class="login-trigger signin-modal" data-modal="modal-login"><?php echo $this->__('LOGIN')?></a></p>
<?php
// Check if current Magento version includes Persistent Shopping Cart Extension
$isPersistantShoppingCartEnabled = Mage::getStoreConfigFlag('persistent/options/enabled');
$isContextCheckout = 0;
if ($isPersistantShoppingCartEnabled) {
    $accountUrl = Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl());
    $isContextCheckout = Mage::helper('checkout')->isContextCheckout();
} else {
    $accountUrl = $this->getCreateAccountUrl();
}
?>



<div class="md-modal md-effect-7 " id="modal-login">
    <!-- new login form s -->

    <div class="loginOutWrap">
        <div class="closeLogin close"><img alt="" src="<?php echo $this->getSkinUrl("images2019/login_close.png");  ?>"></div>
        <div class="loginMain loginMainOut">
            <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
                <?php echo $this->getBlockHtml('formkey'); ?>
                <div style="font-size:14px;color: #847450">您尚未登录</div>
                <div class="loginWel"><img alt="" src="<?php echo $this->getSkinUrl("images2019/login_title.png");  ?>"></div>
                <p>用户名</p>
                <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email loginInp" title="<?php echo $this->__('Email Address') ?>" />
                <p class="clearfix">
                    <span class="ms-fl">密码</span>
                    <span class="ms-fr"><a href="<?php echo $this->getForgotPasswordUrl() ?>">忘记密码</a></span>
                </p>
                <input type="password" name="login[password]" class="input-text required-entry validate-password loginInp" id="pass" title="<?php echo $this->__('Password') ?>" />

                <div class="loginSub clearfix">
<!--                    <div class="loginSubBtn ms-fl">-->
                        <button type="sumbit" class="loginSubBtn ms-fl" style="border: 0px;"> <?php echo $this->__('Login') ?> </button>
<!--                    </div>-->
                    <div class="loginSubNoAccount ms-fl"  >
                        <span>还没有SPALDING账号？</span>
                        <span style="cursor: pointer"><a onclick="window.location='<?php echo $accountUrl ?>'">立即注册 &gt;&gt;</a></span>
                    </div>
                </div>
                <div class="loginOther">
                    联合登录：
                    <a title="使用QQ登录" class="qq" href="<?php echo $this->getUrl('sns/qq/login'); ?>">
                    <!-- melone 修改images->images2019 -->
                        <img alt="" style="margin-right: 5px" src="<?php echo $this->getSkinUrl("images2019/20141209013.png");  ?>">QQ登录
                    </a>
                    <a title="使用支付宝登录" class="alipay" href="<?php echo $this->getUrl('sns/alipay/login'); ?>">
                    <!-- melone 修改images->images2019 -->
                        <img alt="" style="margin-right: 5px" src="<?php echo $this->getSkinUrl("images2019/20141209014.png");  ?>">支付宝登录
                    </a>
                </div>
                <input name="context" type="hidden" value="checkout" />
            </form>
        </div>
    </div>
    <!-- new login form e -->
</div>
<div class="md-overlay"></div>	
	
	
<script type="text/javascript">
    //<![CDATA[
       // var dataForm1 = new VarienForm('login-form', true);
    //]]>
</script>



