<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
<div id="my-account-all">
	<div class="my-account-top clearfix">
		<div class="my-account-welcome">
			<span>
				<?php $customerName = Mage::helper('customer')->getCustomerName() ?>
<!--				--><?php //echo 'Welcome, ' . $customerName ?>
                <?php echo '欢迎, ' . $customerName ?>
			</span>
		</div>
		<div class="my-account-logout">
<!--			<a class="logout-link" href="--><?php //echo $this->getUrl('customer/account/logout', array('_secure' => true)) ?><!--">Log Out</a>-->
            <a class="logout-link" href="<?php echo $this->getUrl('customer/account/logout', array('_secure' => true)) ?>">注销</a>
		</div>
	</div>

	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mobile_my_account_menu')->toHtml(); ?>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>