
<?php

$alipay = Mage::getModel('alipay/payment');
?>

<?php


$orderId = (int) $this->getRequest()->getParam('order_id');

if (!$orderId) {
    $session = Mage::getSingleton('checkout/session');
    $_order = Mage::getModel('sales/order');

    $_order->loadByIncrementId($session->getLastRealOrderId());
}else{


    $_order =Mage::getModel('sales/order')->load($orderId);

    $order_cid=$_order->getCustomerId();
    $current_cid=0;
    if(Mage::helper('customer')->getCustomer()){
        $current_cid=Mage::helper('customer')->getCustomer()->getId();
    }

    if ($current_cid!=$order_cid)
    {
        echo '订单错误，请联系我们';
        exit();
    }
}
$orderId = $_order->getId();
if (!$_order->getId())
{
    echo '订单错误，请联系我们';
    exit();
}
$warnImageSrc =$this->getSkinUrl( "images/warn.png");
?>

<?php
$_customError = false;
$_overSold = false;
$_items = $_order->getItemsCollection();
$_index = 0;
$_count = $_items->count();
$_flag = false;
$isCustomClothes = false;
foreach ($_items as $_item){
    if (!($_item->getParentItem())) {
        
		$_product = $_item->getProduct();        
        
        if(Mage::getModel('customclothes/customClothes')->checkCustomClothesByProdcut($_product)){
        	$isCustomClothes = true;
        }
        
        if ($_product->getIsCustom()) {
            $_flag = true;
            $customOrder = Mage::getModel('custommade/info')->loadByIncrementId($_order->getRealOrderId());
            $customOrderId = $customOrder->getId();
            if (!$customOrderId) {
                $_customError = true;
            }
        }

        $itemQty = (int)Mage::getModel('inventory/physical')->getQtyBySku($_item->getSku());
        if ($itemQty  < 1) {
            $_overSold .= ("<br><h4>商品名称：".$_item->getName()." (".$_item->getSku().")</h4>");
        }
    }
}
?>
<style>
    .payCustomPopUp{position:absolute; z-index:999999;background: rgba(250,250,250,.9);width:960px;height:400px;left:0; top:280px;overflow: hidden;}
    .payPopUpCons{
        color:#847450;
        font-size: 16px;
        margin:80px 20px 50px;
    }
    .payPopUpCons h2{
        font-size: 22px;
        font-weight: bold;
        text-align: center;
        margin:20px 0;
    }
    .payPopUpCons p{
        line-height: 1.6em;
        margin-left:240px;
    }
    .payPopUpConf{
        width:200px;
        height:40px;
        text-align: center;
        background: #00275E;
        color:#D4C89E;
        line-height: 40px;
        font-size: 16px;
        font-weight: bold;
        border-radius: 4px;
        cursor: pointer;
        margin-left:380px;
    }
    .payPopBack{
        font-size: 14px;
        margin-left:450px;
        margin-top:10px;
    }
    .payPopBack a{
        color:#fff;
        text-decoration: underline;
    }
    .payPopBack a:hover{
        color:#f4b201;
    }
</style>
<script>
    jQuery(function(){
        jQuery(".payPopUpConf").click(function(){
            jQuery(this).parent(".payCustomPopUp").css("display","none");
        });
    });
</script>

<div class="shortcut_wrapper">
    <div class="shortcut_price">
        <p class="price">支付金额：<span class="red"><?php echo $this->helper('checkout')->formatPrice($_order->getGrandTotal()) ?> </span></span></p>
        <p><span>类型：<span id="lblType">订单</span></span><span>编号：<span id="lblNo"><?php echo ($_order->getRealOrderId()) ?> </span></span></p>
        <?php if ($_flag): ?>
        <?php $customMsg = Mage::getModel('custommade/info')->loadByIncrementId($_order->getRealOrderId()) ?>
        <div style="color:#847450;padding:10px;font-size:12px;border:1px solid #999;">
            定制一：
            <?php
                       	if($customMsg->getTypeP1() == 1):
                    ?>
                   		<a target="_blank" href="<?php echo $customMsg->getMsg3P1();?>">浏览图片</a>
                    <?php
                        else:
                        if(trim($customMsg->getMsg4P1()) != ''):
                            echo Mage::getModel('custommade/info')->getMsg4PositionResult($customMsg);
                        endif;
                        if(trim($customMsg->getMsg3P1()) != ''):
                            echo '， ' . Mage::getModel('custommade/info')->getMsg4SizeResult($customMsg).'， ';
                        endif;
	                		if ($customMsg->getMsg3P1() == 4):
                        		echo '第一行：' . $customMsg->getMsg1P1();
                    ?>
                    			<br />
                        <?php
                        		echo '第二行：' . $customMsg->getMsg2P1();
                    		else:
                        		echo $customMsg->getMsg1P1();
                    		endif;
                    	endif;
                    ?>
        </div>
         <div class="productsListRow" style="color:#847450;padding:10px;font-size:12px;border:1px solid #999;border-top:0;">
            定制二：
            <?php
                       	if($customMsg->getTypeP2() == 1):
                    ?>
                    	<a target="_blank" href="<?php echo $customMsg->getMsg3P2();?>">浏览图片</a>
                    <?php
                        else:
                            if(trim($customMsg->getMsg4P2()) != ''):
                                echo Mage::getModel('custommade/info')->getMsg4PositionResult($customMsg,2);
                            endif;
                            if(trim($customMsg->getMsg3P2()) != ''):
                                echo '， '.Mage::getModel('custommade/info')->getMsg4SizeResult($customMsg,2).'， ';
                            endif;
                    		if ($customMsg->getMsg3P2() == 4):
                        		echo '第一行：' . $customMsg->getMsg1P2();
                     ?><br />
                        	<?php
                        		echo '第二行：' . $customMsg->getMsg2P2();
                    		else:
                        		echo $customMsg->getMsg1P2();
                    		endif;
                       	endif;
                    ?>
        </div>
        <p class="madeCens"><span>注：定制产品区别于普通产品，订单审核、生产约需25个工作日左右后发出，若时间周期有冲突的顾客，敬请见谅。</span></p>
        <?php endif; ?>
        
        <?php if ($isCustomClothes): ?>
        <style>
            .madeCens{
                /*color:#fff;*/
                color:#847450;
                width:930px;
                font-size: 14px;

            }
            .madeCens th, .madeCens td{
                border:1px solid #666;
                padding:5px;

            }
            .madeCens th{
                font-weight: bold;
                background: #00275E;
                /*background: #333;*/
            }
            .madeCens td{
                color:#847450;
                /*color:#f4b201;*/
            }
        </style>
        
        <table class="madeCens">
            <tr>
                <th>定制内容</th>
            </tr>
              <?php 
        		$customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
            	$dataRow = Mage::getModel('customclothes/order')->loadByIncrementId($_order->getRealOrderId());
        	?>
            <tr>
                <td>
                   	<a target="_blank" href="<?php echo $dataRow->result_image;?>">定制浏览</a>	
                </td>
            </tr>
        </table>
            <p class="madeCens"><span>注：定制产品区别于普通产品，订单审核、生产约需25个工作日左右后发出，若时间周期有冲突的顾客，敬请见谅。</span></p>
        <?php endif; ?>
        
    </div>


    <?php
    if($_order->getStatus() == 'alipay_wait_seller_send_goods'){
        //已经付款成功
        echo '<div class="box">订单已经付款成功</div>';
    }else if($_order->getStatus() == 'canceled'){
        //已经付款成功
        echo '<div class="box">订单已经取消</div>';
    }else if ($_customError) {
        $_shopUrl = $this->getUrl('custom-made.html');
        $_goto = ('<div class="box"><h3>非常抱歉，您的定制信息异常。请前往 <a id="custommadehtml" href="＃" style="cursor:pointer;"> 》》Spalding定制《《 </a> 重新定制您的商品。</h3>');
        $_goto .= ($_overSold.'</div>');
        echo $_goto;
    }else if($_overSold){
        $_shopUrl = $this->getUrl('products.html');
        $_goto = ('<div class="box"><h3>非常抱歉，订单中以下的商品被抢光了。请前往 <a id="productshtml" href="＃"  style="cursor:pointer;"> 》》斯伯丁商城《《 </a> 重新选购您所中意的商品。</h3>');
        $_goto .= ($_overSold.'</div>');
        echo $_goto;
    //需要判断订单状态 如果已经付款成功，直接显示付款成功的提示
    }else {

    ?>
        <?php if ($_flag||$isCustomClothes): ?>
    <div class="payCustomPopUp">
        <div class="payPopUpCons">
            <h2>温馨提示</h2>
            <p>1，由于是个性化定制商品，订单付款后概不退换。</p>
            <p>2，审核后的订单预计将在25个工作日左右生产完成并发货。</p>
<!--            <p>3，定制内容易磨损，建议将定制球作为观赏收藏使用。</p>-->
        </div>
        <div class="payPopUpConf">确认</div>
        <div class="payPopBack"><a href="<?php echo $this->getUrl('sales/order/history/') ?>">暂不付款</a></div>
    </div>
        <?php endif; ?>
    <div class="box">
        <p>点击选择银行<span style="color: #FD5419;"><strong>(信用卡或者网银)</strong></span>前往付款：</p>

        <ul>
<?php
$pay_url = $this->getUrl('alipay/payment/redirect');
$weixinpay_url = $this->getUrl('weixinpay/payment/pay');
$banks_options = Mage::getModel("alipay/source_banks")->getMixed();
$bankChineseTranslate = Mage::getModel("alipay/source_banks")->getChineseTranslate();
foreach($banks_options as $banks_option){
    $value = $banks_option['value'];
    $label = $bankChineseTranslate[$banks_option['label']];
    $code = $banks_option['label'];
    $id = "id".$code;
    $imageSrc = $this->getSkinUrl( "images/bankico/". $code.".gif");
    echo <<<HTML
                        <li>
                        <input id="$id" type="radio" onclick="setBank('$pay_url','$value','$orderId');" name="bank" value="$value">
                        <label for="$id">
                            <img alt="$label" title="$label" src="$imageSrc">
                        </label>
                        </li>
HTML;

}
$alipayImageSrc = $this->getSkinUrl( "images/bankico/alipay.jpg");
$alipayQrImageSrc = $this->getSkinUrl( "images/bankico/alipay_qr.jpg");
$weixinImageSrc = $this->getSkinUrl( "images/pay_weixin.gif");
?>
        </ul>
        <p>点击选择支付平台前往付款：</p>
        <ul>
            <li>
                <input type="radio"  name="bank" checked="checked" id="payment_2" onclick="setBank('<?php echo $pay_url; ?>','alipay','<?php echo $orderId; ?>');">
                <label for="payment_2">
                    <img  id="payimg2" alt="支付宝" title="支付宝" src="<?php echo $alipayImageSrc; ?>">
                </label>
            </li>
            <li>
                <input type="radio"  name="bank" id="payment_3" onclick="setBank('<?php echo $pay_url; ?>','alipay_qrcode','<?php echo $orderId; ?>');">
                <label for="payment_3">
                    <img  id="payimg3" alt="支付宝扫码支付" title="支付宝扫码支付" src="<?php echo $alipayQrImageSrc; ?>">
                </label>
            </li>
            <li>
                <input type="radio"  name="bank" id="payment_4" onclick="setBank('<?php echo $weixinpay_url; ?>','weixin_pay','<?php echo $orderId; ?>');">
                <label for="payment_4">
                    <img  id="payimg4" alt="微信支付" title="微信支付" src="<?php echo $weixinImageSrc; ?>">
                </label>
            </li>
        </ul>
        <div style="text-align: center">
            <a id="submitbutton" class="paymentBtn" target="_blank">我要付款</a>
        </div>
    </div>
    <?php
    }
    ?>
  <div class="bottom_hint">
    <div><a href="<?php echo $this->getUrl('sales/order/view',array('order_id'=>$_order->getId())); ?>" target="_blank">查看订单详情&gt;&gt;</a></div>
    <div class="title">付款遇到问题：</div>
<!--    <p>联系我们 <span class="gray"> 客服帮助您解决支付过程中遇到的困难 <a href="--><?php //echo $this->getUrl('contacts'); ?><!--" target="_blank" >客服中心</a> </span></p>-->
    <p><span class="gray"><a href="<?php echo $this->getUrl('contactus'); ?>" target="_blank" >联系我们&nbsp;&gt;&gt;</a> </span></p>
    <div><a href="http://help.alipay.com/lab/index.htm" target="_blank">支付宝帮助中心&nbsp;&gt;&gt;</a></div>
  </div>
</div>

<div class="popup-wrap popup-orderEnd" style="display:none;" id="go_pay_window">
    <div class="popup-title">
        <h3>温馨提示</h3>
        <a class="btn-popup-close" href="javascript:window_close();"></a>
    </div>
    <div class="tit"></div>
    <div class="popup-cont">
        <div class="msg-tit">
            <i></i>
            请在新打开的页面中完成付款
        </div>
        <div class="msg-text">
            付款完成前请不要关闭此窗口<br>完成付款后请点击下面按钮
        </div>
        <div class="msg-btns">
            <input type="button" value="完成付款" class="actbtn success" onclick="setLocation('<?php echo $this->getUrl('sales/order/view',array('order_id'=>$_order->getId())); ?>')">
            <input type="button" value="付款遇到问题" class="actbtn fail" onclick="setLocation('<?php echo $this->getUrl('contacts'); ?>');">
        </div>
        <div class="bgpay">
            <i></i>
            <a onclick="javascript:window_close();" href="javascript:void(0)">返回选择其它支付方式</a>
        </div>
    </div>
</div>
<script>
    jQuery(document).ready(function(){
        setBank('<?php echo $pay_url; ?>','alipay','<?php echo $orderId; ?>');
        jQuery("#submitbutton").click(function(){
            jQuery.ajax({
                type: 'POST',
                url: '<?php echo $this->getUrl('sales/order/checkstatus');?>',
                data:{
                    order_id:<?php echo $orderId;?>
                },
                dataType: 'json',
                success: function(data){
                    if (data == 'alipay_wait_buyer_pay') {
                        go_pay();
                    } else {
                        alert('该订单已经取消');
                    }
                }
            });
        });

        jQuery('#custommadehtml').click(function(){
            setLocation('<?php echo $this->getUrl('custom-made.html'); ?>');
            return false;
        });
        jQuery('#productshtml').click(function(){
            setLocation('<?php echo $this->getUrl('products.html'); ?>');
            return false;
        });
    });
</script>
