<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/custom.js'); ?>"></script>
<?php $_product = $this->getProduct(); ?>
<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
    <!-- 定制背景 -->
    <div class="bodyBg_cusMade">
        <img style="width:100%;" src="<?php echo $this->getSkinUrl('images/customMade/cBg2.jpg');  ?>" alt="">
    </div>

    <!-- 定制主框架 -->
    <!-- 第一步 开始定制 -->
    <div class="cusMadeCons madeStep_1" style="display:none;">
        <div class="cusMadeBox cusMadeCen">
            <div class="step_1_ball"><img src="<?php echo $this->getSkinUrl('images/customMade/step_1_ball.png');  ?>" alt=""></div>
            <div class="step_1_Btn"><a href="javascript:;"><img src="<?php echo $this->getSkinUrl('images/customMade/step_1_ballBtn.png');  ?>" alt=""></a></div>
        </div>
        <div class="cusMadeBox cusMadeRig">
            <div class="madeBoxVal">
                <h1>SPALDING 74-604 ID</h1>
<!--                <h2>价格：￥--><?php //echo $_taxHelper->getPrice($_product, $_product->getPrice()) ?><!--</h2>-->
                <h2>价格：￥200</h2>
            </div>

            <div class="madeBoxCons">
                <h3>可定制球皮</h3>
                <p>“掌控”系列的经典之作，销量之王，性价比之王，超强PU超耐磨，室内外通用，恰到好处的粘度让你轻松“掌控”比赛！</p>
                <dl class="prods">
                    <dd>产品特点</dd>
                    <dt>添加图案</dt>
                    <dt>定制专属签名</dt>
                </dl>
                <div class="madeServ">斯伯丁定制退换货服务</div>
                <div class="madeDate">该产品定制将在4-6周内送货上门</div>
            </div>
            <div class="madeFuns">
                <button>开始定制</button>
            </div>
        </div>
    </div>

    <!-- 第二步  定制参数-->
    <div class="cusMadeCons madeStep_2">
        <?php echo $this->getChildHtml('custommade_view_options') ?>
    </div>
    
    <div class="madeBotmSn">
        <h1>定制专属篮球</h1>
        <p>斯伯丁74-604“掌控”系列的经典之作，销量之王，性价比之王，超强PU超耐磨，室内外通用，<br>恰到好处的粘度让你轻松“掌控”比赛！</p>
    </div>

</form>
