<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');

    $_lightboxConfig = Mage::getStoreConfig('easy_lightbox/general');
    /* Main Image Size */
    if (strstr($_lightboxConfig['mainImageSize'], '_')) {
        $mainImageSize = explode('_', $_lightboxConfig['mainImageSize'], 2);
    } else {
        $mainImageSize = array(265, 265);
    }
    /* Popup Image Size */
    if (strstr($_lightboxConfig['popupImageSize'], '_')) {
        $popupImageSize = explode('_', $_lightboxConfig['popupImageSize'], 2);
    } else {
        $popupImageSize = array(0, 0);
    }
    /* Additional Images Size */
    if (strstr($_lightboxConfig['additionalImageSize'], '_')) {
        $additionalImageSize = explode('_', $_lightboxConfig['additionalImageSize'], 2);
    } else {
        $additionalImageSize = array(60, 60);
    }

    $image = $this->helper('catalog/image')->init($_product, 'image');
    if ($popupImageSize[0] > 0) {
        $image = $this->helper('catalog/image')->init($_product, 'image')->resize($popupImageSize[0], $popupImageSize[1]);
    }

    $urlKey = $_product->getUrlKey();

?>

<div id="detailPixWrap">
    <a rel="productGallery [gallery]" href="http://image.sneakerhead.com/is/image/sneakerhead/<?php echo $this->htmlEscape($_product->getUrlKey()) ?>-1">
        <img width="330" id="mainImage" src="http://image.sneakerhead.com/is/image/sneakerhead/detail-big-image?&$detail_big_image$&layer=2&src=sneakerhead/<?php echo $this->htmlEscape($_product->getUrlKey()) ?>-1"
             alt="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"
             onMouseOver="javascript:sku=1"  data-zoom-image="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>"/></a>
    <div class="detailArrowPrev">
        <a class="detailArrowPrevBtn" href="javascript:void(0)"></a>
    </div>
    <div class="detailImageReelWindow">
        <div class="detailImageReel">
            <div id="detailProductGallery">
                <?php $imageCount = floor($_product->getImageCount()) ?>
                <?php $i = 0 ?>
                <?php while ($i++ < $imageCount) : ?>
                    <div>
                        <a rel="productGallery [gallery]" onMouseOver="javascript:sku=<?php echo $i ?>;">
                            <img src="http://image.sneakerhead.com/is/image/sneakerhead/viewer_thumbnail_template?&$viewer_thumbnail_image_preset$&layer=2&src=sneakerhead/<?php echo $this->htmlEscape($_product->getUrlKey()) ?>-<?php echo $i ?>" alt=""/>
                        </a>
                    </div>
                <?php endwhile ?>
            </div>
        </div>
    </div>
    <div class="detailArrowNext">
        <a class="detailArrowNextBtn" href="javascript:void(0)"></a>
    </div>
    <div id="detailPixIconWrap"></div>
</div>


<?php if(!$_lightboxConfig['defaulzoom']): ?>

<?php
	$maintitle = $this->htmlEscape($_product->getImageLabel());
	if(($_lightboxConfig['productName'] != 0) && empty($maintitle)):
	        $maintitle  = $_product->getName();
	endif;
?>

<?php endif; ?>

<?php //if (count($this->getGalleryImages()) > 0): ?>
<!--<div class="more-views">-->
<!--    <h4>--><?php //echo $this->__('More Views') ?><!--</h4>-->
<!--    <ul>-->
<!--    --><?php //foreach ($this->getGalleryImages() as $_image): ?>
<!--	--><?php
//	$subtitle = $this->htmlEscape($_image->getLabel());
//	if(($_lightboxConfig['productName'] != 0) && empty($subtitle)):
//	        $subtitle  = $_product->getName();
//	endif;
//	?>
<!--    <li>-->
<!--        <a href="--><?php //echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($popupImageSize[0], $popupImageSize[1]); ?><!--"-->
<!--            rel="lightbox[rotation]"-->
<!--            title="--><?php //echo $subtitle; ?><!--"-->
<!--            onclick="return false;"-->
<!--        ><img src="--><?php //echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($additionalImageSize[0], $additionalImageSize[1]); ?><!--" alt="--><?php //echo $subtitle; ?><!--"-->
<!--        /></a>-->
<!--    </li>-->
<!--    --><?php //endforeach; ?>
<!--    </ul>-->
<!--</div>-->
<?php //endif; ?>

<script type="text/javascript">
jQuery('#mainImage').elevateZoom();
</script>