<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');

    $_lightboxConfig = Mage::getStoreConfig('easy_lightbox/general');
    /* Main Image Size */
    if (strstr($_lightboxConfig['mainImageSize'], '_')) {
        $mainImageSize = explode('_', $_lightboxConfig['mainImageSize'], 2);
    } else {
        $mainImageSize = array(265, 265);
    }
    /* Popup Image Size */
    if (strstr($_lightboxConfig['popupImageSize'], '_')) {
        $popupImageSize = explode('_', $_lightboxConfig['popupImageSize'], 2);
    } else {
        $popupImageSize = array(0, 0);
    }
    /* Additional Images Size */
    if (strstr($_lightboxConfig['additionalImageSize'], '_')) {
        $additionalImageSize = explode('_', $_lightboxConfig['additionalImageSize'], 2);
    } else {
        $additionalImageSize = array(60, 60);
    }

    $image = $this->helper('catalog/image')->init($_product, 'image');
    if ($popupImageSize[0] > 0) {
        $image = $this->helper('catalog/image')->init($_product, 'image')->resize($popupImageSize[0], $popupImageSize[1]);
    }

    $urlKey = $_product->getUrlKey();
    $pSku = $_product->getSku();

?>

<div id="detailPixWrap">
    <a rel="productGallery [gallery]" >
        <img width="330" id="mainImage" data-zoom-image="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>media/catalog/product/<?php echo $pSku."/". $urlKey ?>-1.jpg"
             src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>media/catalog/product/<?php echo $pSku."/". $urlKey ?>-5.jpg"
             alt="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"
             onMouseOver="javascript:sku=1" /></a>
    <div class="detailArrowPrev">
        <a class="detailArrowPrevBtn" href="javascript:void(0)"></a>
    </div>
    <div class="detailImageReelWindow">
        <div class="detailImageReel">
            <div id="detailProductGallery">
                <?php $imageCount = floor($_product->getImageCount()) ?>
                <?php $i = 0 ?>
                <?php while ($i++ < $imageCount) : ?>
                    <div>
                        <a rel="productGallery [gallery]" onMouseOver="javascript:sku=<?php echo $i ?>;">
<!--                            <img src="http://s7d5.scene7.com/is/image/sneakerhead/spalding50px?$50x50$&$image50=--><?php //echo $this->htmlEscape($_product->getUrlKey()) ?><!-----><?php //echo $i ?><!--" alt=""/>-->
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>media/catalog/product/<?php echo $_product->getSku()."/". $this->htmlEscape($_product->getUrlKey()) ?>-<?php echo $i+7 ?>.jpg" alt=""/>
                        </a>
                    </div>
                <?php endwhile ?>
            </div>
        </div>
    </div>
    <div class="detailArrowNext">
        <a class="detailArrowNextBtn" href="javascript:void(0)"></a>
    </div>
    <div id="detailPixIconWrap"></div>
</div>


<?php if(!$_lightboxConfig['defaulzoom']): ?>

<?php
	$maintitle = $this->htmlEscape($_product->getImageLabel());
	if(($_lightboxConfig['productName'] != 0) && empty($maintitle)):
	        $maintitle  = $_product->getName();
	endif;
?>

<?php endif; ?>
<script type="text/javascript">
jQuery('#mainImage').elevateZoom();
</script>