<?php
$homeUrl = Mage::helper('core/url')->getHomeUrl();
?>
<input type="hidden" id="codeMessageReturn">
<!--<div class="header_fix position_re"></div>-->
<div class="slide-group position_re">
    <div id="step1" class="slide1 authen_step position_re">
        <div class="main-container container_step position_re">
            <div class="content" style="width: 1516px;margin: 0 auto;">
                <img style="position:relative;top: 34px;z-index: 100;" src='<?php echo $this->getSkinUrl("images2019/authentication/titleauth.png") ?>'>
               <!--<?php echo "<img class='auth_box' src='" . $this->getSkinUrl('images2019/authentication/box_01.png') . "'>"; ?>-->

                <?php echo "<img class='auth_box' src='" . $this->getSkinUrl('images2019/authentication/box.png') . "'>"; ?>
                <div class="content_detail position_re">
                    <span class="security_authentication_test">斯伯丁防伪验证系统</span>
                    <!--                    --><?php //echo "<img class='auth_title position_re' src='" . $this->getSkinUrl('images/authentication/font.png') . "'>"; ?>
                    <!--<h2>斯伯丁体育用品（中国）有限公司正式启用防伪芯片标签，请按您购买的防伪标签类型选取不同的验证方式   如您购买的是防伪芯片标签，则需要使用带有NFC功能的手机进行扫描</h2>-->

                   <div style="color: #847450;margin-bottom: 63px;">
                    <div style="line-height: 30px;">斯伯丁体育用品（中国）有限公司正式启用防伪芯片标签，请按您购买的防伪标签类型选取不同的验证方式   </div>
                    <div style="line-height: 30px;">如您购买的是防伪芯片标签，则需要使用带有NFC功能的手机进行扫描</div>
                   </div>
                    <div class="validate_type">
                        <div style="margin-top: -40px;"><?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/code_01.png') . "'>"; ?></div>
                        <!--                        <h2 class=" ">新防伪码</h2>-->
                        <div><img src='<?php echo $this->getSkinUrl("images2019/button-1.png") ?>' alt="" id="security_chip" class="security_chip" style="margin-top: 20px;margin-right: 95px;"></div>
                        <!--                        <img src='--><?php //echo $this->getSkinUrl("images2019/button-1.png") ?><!--' alt="" id="oldAuthenticationButton" class="validate_type_old">-->
                        <!--                        <button id="newAuthenticationButton" class="validate_type_new">新版验证</button>-->
                    </div>
                    <div class="validate_type" style="margin-top: 26px;">
                        <div style="margin-top: 2px;"><?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/code_02.png') . "'>"; ?></div>
                        <!--                        <h2 class=" ">旧防伪码</h2>-->
                        <div><img src='<?php echo $this->getSkinUrl("images2019/button-2.png") ?>' alt="" id="newAuthenticationButton" class="validate_type_new" style="margin-top: 35px;margin-left: 85px;"></div>
                        <!--                        <button id="oldAuthenticationButton" class="validate_type_old"-->
                        <!--                                data-reveal-id='alertOldValidation'>旧版验证-->
                        <!--                        </button>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="step2" class="slide1 authen_step position_re">
        <div class="main-container container_step position_re">
        <img src='<?php echo $this->getSkinUrl("images2019/authentication/title.png") ?>' alt="" style="padding-top: 108px;" >
        <div class="content">
                <img  class="auth_box" style="width:1000px;margin-top: 65px;" src='<?php echo $this->getSkinUrl("images2019/authentication/box_02.png") ?>'>
                <div class="content_detail position_re">
                    <div style="margin-top: 200px;"><?php echo "<img class='auth_logo position_re' src='" . $this->getSkinUrl('images2019/authentication/icon.png') . "'>"; ?></div>
                    <form class="code_area position_re" name="valid_code_input" style="position:relative;z-index: 1;">
                        <b class="position_re">防伪码:</b><input type="text" id="barCode" class="valid_check_code"
                                                              maxlength="14" placeholder="请输入12或14位的防伪码" style="margin-top: 50px">
                                                              <!--style="margin-top: 44px">-->
                        <span id="barCodeMSG" style="opacity: 0;width:100%;height:28px;line-height:28px;padding:0;">必填</span>
                        <b class="position_re">验证码:</b><input type="text" id="verifyCode" class="verifyCode valid_code"
                                                              maxlength="4" placeholder="请输入4位的验证码" >
                        <img src="<?php echo $this->getUrl('code_num.php', array('_secure' => true)) ?>" id="getCodeNum"
                             align="absmiddle">
                        <span id="verifyCodeMSG" style="opacity: 0;width:100%;height:28px;line-height:28px;padding:0;">必填</span>

                        <img src='<?php echo $this->getSkinUrl("images2019/authentication/immediately_verify.png") ?>' alt="" id="authenticationSubmitButton"  class="btn_valid position_re"
                             data-reveal-id="alertValidRightNow" style="width: 178px;margin-top: 22px;">
                    </form>

                    <!--                    <button id="authenticationSubmitButton" class="btn_valid position_re"-->
                    <!--                            data-reveal-id="alertValidRightNow">立即验证-->
                    <!--                    </button>-->
                <div class="df jcc aic" style="position: relative;bottom: -146px;z-index: 10;">
                  <img src='<?php echo $this->getSkinUrl("images2019/authentication/return.png") ?>' alt="" style="width: 98px;" id="return">
                </div>
                 <button id="cheshi" style="width: 100px;height: 37px;position: relative;bottom: -54px;z-index: 100;">按钮</button>
             </div>


            </div>

            <div class="step2ball df jcsb">
                   <img src='<?php echo $this->getSkinUrl("images2019/authentication/ball-left.png") ?>' alt="" >
                   <img src='<?php echo $this->getSkinUrl("images2019/authentication/ball-right.png") ?>' alt="" >
            </div>



        </div>
    </div>

<!--top: 90px;-->
    <div id="step22" class="authen_step position_re" style="height: 1068px;">
        <div class="main-container22 container_step22 position_re">
            <div class="content22" style="height: 1068px">
               <!-- <div style="margin-bottom:34px;margin-top: 32px;" class="df jcc aic">
                    <span class="instructions df jcc aic">防伪芯片验证使用说明</span>
                </div>-->
               <div class="step22img"> <?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/title.png') . "'>"; ?></div>
                <div class="pannel-hd df jcsb">
                   <div class="item_lt">
                       <div class="it_box df">
                                <?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/button-step1.png') . "'>"; ?>
<!--                            <div class="box_p" style="margin-top: 20px;">-->
<!--                    <span>-->
<!--                    使用手机的NFC功能对准防伪芯片进行感应。Android手机先打开手机NFC功能，在手机【设置】|【设备连接】中开启NFC选项。iPhone7\8\8plus\X 需要下载并打开NFCTagInfo APP；iPhone XR以上已默认开启NFC功能。-->
<!--                </span>-->
<!--                            </div>-->
                        </div>
                    </div>
                    <div class="item_lt">
                        <div class="it_box df">
                            <?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/button-step2.png') . "'>"; ?>
<!--                            <div class="box_p" style="margin-top: 50px;">-->
<!--                    <span>-->
<!--                   扫描后出现登录页面，输入手机号和验证码后点击“下一步”进入验证结果页面。-->
<!--                </span>-->
<!--                            </div>-->
                        </div>
                    </div>
                    <div class="item_lt">
                        <div class="it_box df">
                            <?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/button-step3.png') . "'>"; ?>
<!--                            <div class="box_p" style="margin-top: 50px;">-->
<!--                            <span>-->
<!--                              进入验证结果页面后，如果验证成功会显示通过验证 可以看到这颗球的图片、名称等产品信息。-->
<!--                            </span>-->
<!--                            </div>-->
                        </div>
                    </div>
                    <div class="item_lt">
                        <div class="it_box df">
                            <?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/button-step4.png') . "'>"; ?>
<!--                            <div class="box_p" style="margin-top: 50px;">-->
<!--                                <span>-->
<!--                                点击查看此产品，可以看到产品图片。-->
<!--                               </span>-->
<!--                            </div>-->
                        </div>
                    </div>
                </div>
                <div class="pannel-ft df jcsb">
                    <?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/img-step1.png') . "'>"; ?>
                    <?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/img-step2.png') . "'>"; ?>
                    <?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/img-step3.png') . "'>"; ?>
                    <?php echo "<img class=' ' src='" . $this->getSkinUrl('images2019/authentication/img-step4.png') . "'>"; ?>
                </div>

                <div class="df jcc aic" style="width: 1506px">
                    <img src='<?php echo $this->getSkinUrl("images2019/authentication/return.png") ?>' alt="" style="width: 98px;margin-top: 51px;" id="return_1">
                </div>
            </div>
        </div>
    </div>

    <div id="step3" class="slide1 authen_step position_re">
        <div class="main-container container_step position_re">
            <div class="content">
                <?php echo "<img class='auth_box' src='" . $this->getSkinUrl('images2019/authentication/box_03.png') . "'>"; ?>
                <div class="content_detail position_re">
                   <!-- <?php echo "<img class='auth_logo position_re' src='" . $this->getSkinUrl('images/authentication/code.gif') . "'>"; ?>-->
                    <img class="auth_logo position_re" style="width: 100%;" src='<?php echo $this->getSkinUrl("images/authentication/code.gif") ?>'>
                    <div class="selection_area position_re">
                        <p>您购买商品的防伪标签上，在转动不同角度观看方框内褐色部分内容时，能否看到如下图所示 “S”英文字母的隐藏效果？</p>

                        <p class="sel_checkbox">
                            <span
                                id="q_1_true"><?php echo "<img class='q_1_true' src='" . $this->getSkinUrl('images2019/authentication/true.png') . "'>"; ?></span>是
                            <span
                                id="q_1_false"><?php echo "<img class='q_1_false' src='" . $this->getSkinUrl('images2019/authentication/true.png') . "'>"; ?></span>否
                            <b id="isQ1Selected" style="opacity: 0">必填</b>
                        </p>

                        <p>您购买商品的防伪标签上，以手指触摸方框内褐色部分内容时，是否有明显凹凸感？</p>

                        <p class="sel_checkbox">
                            <span
                                id="q_2_true"><?php echo "<img class='q_2_true' src='" . $this->getSkinUrl('images2019/authentication/true.png') . "'>"; ?></span>是
                            <span
                                id="q_2_false"><?php echo "<img class='q_2_false' src='" . $this->getSkinUrl('images2019/authentication/true.png') . "'>"; ?></span>否
                            <b id="isQ2Selected" style="opacity: 0">必填</b>
                        </p>
                    </div>
<!--                    <button id="authenticationCommitButton" class="btn_submit position_re">提交验证</button>-->

                    <img src='<?php echo $this->getSkinUrl("images2019/authentication/submit_button.png") ?>' alt="" id="authenticationCommitButton" class="btn_submit position_re" style="width: 178px;">
                </div>
            </div>
        </div>
    </div>
    <div id="step4" class="slide1 authen_step position_re">
        <div class="main-container container_step position_re">
            <div class="content">
                <?php echo "<img class='auth_box' src='" . $this->getSkinUrl('images2019/authentication/box_03.png') . "'>"; ?>
                <div class="content_detail position_re">
                    <h3 id="validResultContent"></h3>

                    <div class="selection_btn_area position_re">
                        <a id="reEditButton" class="btn_edit position_re">修改答案</a>
                        <a href="<?php echo $this->getUrl('/'); ?>" class="btn_return position_re">返回首页</a>
                        <a id="contactUsButton" class="btn_contact position_re" data-reveal-id="alertContactUs">
                            联系我们
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="alertOldValidation" class="reveal-modal xlarge">
    <h1>旧版防伪标签请拨打电话<span>4000801876</span>进行自助查询</h1>
    <a class="close-reveal-modal">×</a>
</div>
<div id="alertValidRightNow" class="reveal-modal xlarge">
    <h1 style="color: #847450;"></h1>
    <a class="close-reveal-modal">×</a>
</div>
<div id="alertContactUs" class="reveal-modal large">
    <h2 style="color: #00275E;">商品验证序列:<span id="valid_check_code">&nbsp;&nbsp;</span></h2>

    <form action="">
        <ul>
            <li>
                <label for="username">* 姓&nbsp;&nbsp;&nbsp;&nbsp;名</label>
                <input type="text" id="username" class="required">
                <span class="formTips_username"></span>
            </li>
            <li>
                <label for="tel">* 电话号码</label>
                <input type="text" id="tel" class="required" maxlength="12" placeholder="请正确填写电话号码">
                <span class="formTips_tel"></span>
            </li>
            <li>
                <label for="email">* 电子邮件</label>
                <input type="email" id="email" class="required" placeholder="请正确填写电子邮件">
                <span class="formTips_email"></span>
            </li>
            <li>
                <label>* 问题类型</label>
                <input type="text" value="防伪验证" id="question_type" class="required" readonly>
                <span class="formTips_type"></span>
            </li>
            <li>
                <label>* 购买商店</label>
                <input type="text" id="purchase_shop" class="required">
                <span class="formTips_shop"></span>
            </li>
            <li>
                <label>* 购买国家</label>
                <input type="text" value="China" id="purchase_countury" class="required" readonly>
                <span class="formTips_countury"></span>
            </li>
            <li>
                <label>* 问题描述</label>
                <textarea rows="3" cols="" id="question_desc" class="required" style="resize: none;"></textarea>
                <span class="formTips_desc"></span>
            </li>
            <li>
                <label>*&nbsp;验&nbsp;证&nbsp;码</label>
                <input type="text" id="validCode" class="required" maxlength="4">
                <img style="cursor: pointer"
                     src="<?php echo $this->getUrl('code_num_verify.php', array('_secure' => true)) ?>"
                     id="getCodeNumContact" align="absmiddle">
                <span class="formTips_validCode"></span>
            </li>
        </ul>
        <button type="submit" value="提交" id="send">发送问题</button>
        <b>有任何问题？请填写虾面数据我们会尽快回复您或者拨打客服热线：<span>4000801876</span></b>
    </form>
    <a class="close-reveal-modal">×</a>
</div>
<script>
    jQuery('#send').on('click', function (e) {
        var verifyCode = jQuery('#validCode').val();
        var verifyCodeCheck = false;
        //check 验证码
        jQuery.ajax({
            async: false,
            type: 'POST',
            url: '<?php echo $homeUrl;?>barcodeVerifyCode.php',
            data: {verifyCode: verifyCode},
            success: function (data) {
                if (data == 'success') {
                    //验证码正确
                    verifyCodeCheck = true;
                } else {
                    //验证码不正确
                    jQuery('.formTips_validCode')[0].innerHTML = verifyCode == '' ? '必填' : '验证码错误';
                    getCodeNumContact();
                }
            },
            error: function () {
                getCodeNumContact();
            }
        });
        if (verifyCodeCheck) {
            jQuery('.formTips_validCode')[0].innerHTML = '';
            //验证数据
            var name = jQuery("#username").val();
            var tel = jQuery("#tel").val();
            var email = jQuery("#email").val();
            var questionType = jQuery("#question_type").val();
            var store = jQuery("#purchase_shop").val();
            var country = jQuery("#purchase_countury").val();
            var desc = jQuery("#question_desc").val();
            var inputData = {
                name: name,
                email: email,
                tel: tel,
                questionType: questionType,
                store: store,
                country: country,
                desc: desc
            };

            //需要验证
            contact_validation(inputData);
            //验证通过提交数据

            jQuery(this).attr('disabled', 'disabled');

            jQuery.ajax({
                type: 'POST',
                url: '<?php echo $this->getUrl('store/index/saveAuthentication'); ?>',
                data: {
                    name: name,
                    email: email,
                    tel: tel,
                    questionType: questionType,
                    store: store,
                    country: country,
                    desc: desc
                },
                success: function (result) {
                    if (result == 'success') {
//                        alert(result);
                        jQuery('#alertContactUs')[0].style.display = 'none';
                        jQuery('.reveal-modal-bg')[0].style.display = 'none';
                    } else {
                        alert(result);
                    }
                    jQuery('#send').removeAttr("disabled");

                },
                error: function () {
                    jQuery('##send').removeAttr("disabled");
                }
            });

        }

        return false;
    });
    jQuery('#newAuthenticationButton').on('click', function (e) {
        //	新版验证 只是调到下一步 不弹出modal框架
        jQuery('.slide-group').animate({'top': '-1068px'});
        jQuery("#step2").css("display","block");
        jQuery("#step22").css("display","none");
    });
    jQuery('#security_chip').on('click', function (e) {
        //	新版验证 只是调到下一步 不弹出modal框架
        jQuery('.slide-group').animate({'top': '-1068px'});
        jQuery("#step2").css("display","none");
        jQuery("#step22").css("display","block");
    });
    jQuery('#return').on('click', function (e) {
        jQuery('.slide-group').animate({'top': '90px'});
    });
    jQuery('#return_1').on('click', function (e) {
        jQuery('.slide-group').animate({'top': '90px'});
    });
   jQuery('#cheshi').on('click', function (e) {
       jQuery('.slide-group').animate({'top': '-2136px'});
   });
    jQuery('#oldAuthenticationButton,#contactUsButton').on('click', function (e) {
        jQuery('#alertContactUs')[0].style.display = 'block';
        jQuery('#valid_check_code')[0].innerHTML = jQuery.trim(jQuery('#barCode').val());
        var modalLocation = jQuery(this).attr('data-reveal-id');
        jQuery('#' + modalLocation).reveal(jQuery(this).data());
    });
    jQuery('#authenticationSubmitButton').on('click', function (e) {
        jQuery('#barCodeMSG').removeClass('activeBarCode');
        jQuery('#verifyCodeMSG').removeClass('activeVerifyCode');
        //验证数据
        var barCode = jQuery.trim(jQuery('#barCode').val());
        var verifyCode = jQuery.trim(jQuery('#verifyCode').val());
        if (barCode == '' || verifyCode == '' || (barCode.length != 12 && barCode.length != 14) || verifyCode.length < 4) {
            //提示错误信息
            if (barCode == '') {
                if (jQuery('.activeBarCode').length == 0 || jQuery('.activeBarCode')[0].innerHTML != '防伪码必填') {
                    jQuery('#barCodeMSG').addClass('activeBarCode');
                    jQuery('.activeBarCode')[0].innerHTML = '防伪码必填';
                }
            }
            if (verifyCode == '') {
                if (jQuery('.activeVerifyCode').length == 0 || jQuery('.activeVerifyCode')[0].innerHTML != '验证码必填') {
                    jQuery('#verifyCodeMSG').addClass('activeVerifyCode');
                    jQuery('.activeVerifyCode')[0].innerHTML = '验证码必填';
                }
            }
            if (barCode != '' && barCode.length != 12 && barCode.length != 14) {
                jQuery('#barCodeMSG').addClass('activeBarCode');
                jQuery('.activeBarCode')[0].innerHTML = '请输入12或14位的防伪码';
            }
            if (verifyCode != '' && verifyCode.length < 4) {
                jQuery('#verifyCodeMSG').addClass('activeVerifyCode');
                jQuery('.activeVerifyCode')[0].innerHTML = '请输入4位的验证码';
            }

            // 页面停止跳转下一页
            jQuery('.slide-group').animate({'top': '-1086px'});
        } else {
            jQuery('#barCodeMSG')[0].innerHTML = jQuery('#verifyCodeMSG')[0].innerHTML = '';

            //var verifyResult = "";
            jQuery.ajax({
                async: false,
                type: 'POST',
                url: '<?php echo $homeUrl;?>barcodeVerify.php',
                data: {barcode: barCode, verifycode: verifyCode},
                success: function (data, textStatus) {
                    jQuery('#authenticationSubmitButton').removeAttr("disabled");
                    if (data == "1") {
                        //验证码不正确
//                        alert("验证码不正确");
                        jQuery('#verifyCodeMSG').addClass('activeVerifyCode');
                        jQuery('.activeVerifyCode')[0].innerHTML = '验证码错误';
                    }
                    else {
                        var msg = data;
//                    	if(barCode.length == 12){
//                        	var url = "http://query.t-secu.net/frontPages/jsp/customers/spalding.jsp";
//						}else if(barCode.length == 14){
//							var url = "http://query.t-secu.net/frontPages/jsp/customers/spalding.jsp";
//						}
//                    	jQuery.ajax({
//                            headers: {
//                                Accept : "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
//                            },
//                            url: url,
//                            crossDomain: true,
//                            type: "POST",
//                            contentType: "application/x-www-form-urlencoded; charset=UTF-8",
//                            data: {
//                                code: barCode
//                            },
//                            error : function(){
//                                alert('Error');
//                            },
//                            success: function(msg){
                        var append = "<html><body><div>" + msg + "</div></body></html>";
                        var myJSON = jQuery(append).find("#decryString").text();
                        var data = jQuery.parseJSON(myJSON);
                        if (!data || !data.detemVal) {
                            var messageShow = "<注意!!> 防伪码不存在或被多次查询，详细信息请拨打4000801876-防伪查询-假球投诉或建议, 进行查询。";
                            jQuery('#alertValidRightNow>h1')[0].innerHTML = messageShow;
                            jQuery('#alertValidRightNow').reveal(messageShow);
                        }else if (data.detemVal == 'F') {
                            if (myJSON.indexOf("防偽碼正確") > 0) {
                                var messageShow = "<注意!!> " + data.authCode + " 该商品验证码已超过规定查询次数，谨防假冒！！如有疑问请拨打咨询电话4000801876。";
                            } else {
//                                var messageShow = "<注意!!> " + data.authCode + " 您查询的商品验证码不存在，谨防假冒!!如有疑问请拨打咨询电话4000801876。";
                                var messageShow = "<注意!!> " + data.authCode + " 此码不存在或被多次查询，详细信息请拨打4000801876-防伪查询-假球投诉或建议, 进行查询。";
                            }
                            jQuery('#alertValidRightNow>h1')[0].innerHTML = messageShow;
                            jQuery('#alertValidRightNow').reveal(messageShow);
                        } else {
                            switchCondition(jQuery("#authenticationSubmitButton"));
                        }
//                            }
//                    	});
                    }
//                     else if (data == "2") {
//                         //验证码正确
//                         switchCondition(jQuery("#authenticationSubmitButton"));
//                     } else {

//                         //弹出错误信息
//                         jQuery('#alertValidRightNow>h1')[0].innerHTML = data;
//                         jQuery('#alertValidRightNow').reveal(data);
//                     }
                    //switchCondition(jQuery("#authenticationSubmitButton"));
                },
                error: function () {
                    alert('Error');
                    jQuery('#authenticationSubmitButton').removeAttr("disabled");
                },
                complete: function (XMLHttpRequest, textStatus) {
                    getCodeNum();
                }
            });
        }

    });
    //刷新验证码
    jQuery('#getCodeNum').on('click', function (e) {
        getCodeNum();
    });
    function getCodeNum() {
        jQuery('#getCodeNum').attr("src", '<?php echo $homeUrl;?>code_num.php?' + Math.random());
    }
    function getCodeNumContact() {
        jQuery("#getCodeNumContact").attr("src", '<?php echo $homeUrl;?>code_num_verify.php?' + Math.random());
    }
    jQuery('#getCodeNumContact').on('click', function (e) {
        getCodeNumContact();
    });
    jQuery('#authenticationCommitButton').click(function () {
        // 验证有没有选则，如果没有显示提示信息，如果选择了，跳转下一步
        var q1TrueIsSelected = jQuery('.q_1_true')[0].style.display;
        var q1FalseIsSelected = jQuery('.q_1_false')[0].style.display;
        var q2TrueIsSelected = jQuery('.q_2_true')[0].style.display;
        var q2FalseIsSelected = jQuery('.q_2_false')[0].style.display;

        if (q1TrueIsSelected == q1FalseIsSelected || q2TrueIsSelected == q2FalseIsSelected) {
            jQuery('#isQ1Selected')[0].style.opacity = q1TrueIsSelected == q1FalseIsSelected ? 1 : 0;
            jQuery('#isQ2Selected')[0].style.opacity = q2TrueIsSelected == q2FalseIsSelected ? 1 : 0;
            jQuery('.slide-group').animate({'top': '-1920px'});
        } else {
            jQuery('#isQ1Selected')[0].style.opacity = jQuery('#isQ2Selected')[0].style.opacity = 0;
            if (q1TrueIsSelected == q2TrueIsSelected && q2TrueIsSelected == 'inline') {
                jQuery('#validResultContent')[0].innerHTML = '感谢您的购买，系统判定此为原厂正品，请放心使用。'
            }
            if (q1TrueIsSelected == q2FalseIsSelected && q2FalseIsSelected == 'inline') {
                jQuery('#validResultContent')[0].innerHTML = '感谢您的耐心配合，请拨打400电话或点击『联络我们』留下您的联络方式，我们将有专人协助您做进一步鉴定。'
            }
            if (q1FalseIsSelected == q2TrueIsSelected && q2TrueIsSelected == 'inline') {
                jQuery('#validResultContent')[0].innerHTML = '感谢您的耐心配合，请点击『联络我们』留下您的联络方式，我们将有专人协助您做进一步鉴定。'
            }
            if (q1FalseIsSelected == q2FalseIsSelected && q2FalseIsSelected == 'inline') {
                jQuery('#validResultContent')[0].innerHTML = '感谢您的耐心配合，请点击『联络我们』留下您的联络方式，我们将有专人协助您做进一步鉴定。'
            }
            jQuery('.slide-group').animate({'top': '-2880px'});
        }
    })
    jQuery('#reEditButton').click(function () {
        jQuery('.slide-group').animate({'top': '-1920px'});
    })
    jQuery.fn.reveal = function (options) {

        var defaults = {
            animation: 'fadeAndPop',
            animationspeed: 100,
            closeonbackgroundclick: true,
            dismissmodalclass: 'close-reveal-modal'
        };

        var options = jQuery.extend({}, defaults, options);

        return this.each(function () {
            var modal = jQuery(this),
                topMeasure = parseInt(modal.css('top')),
                topOffset = modal.height() + topMeasure,
                locked = false,
                modalBG = jQuery('.reveal-modal-bg');

            if (modalBG.length == 0) {
                modalBG = jQuery('<div class="reveal-modal-bg">').insertAfter(modal);
            }

            modal.on('reveal:open', function () {
                modalBG.off('click.modalEvent');
                jQuery('.' + options.dismissmodalclass).off('click.modalEvent');
                if (!locked) {
                    lockModal();
                    modal.css({'top': jQuery(document).scrollTop() - topOffset, 'opacity': 0, 'visibility': 'visible'});
                    modalBG.fadeIn(options.animationspeed / 2);
                    modal.delay(options.animationspeed / 2).animate({
                        "top": jQuery(document).scrollTop() + topMeasure + 'px',
                        "opacity": 1
                    }, options.animationspeed, unlockModal());
                }
                modal.off('reveal:open');
            });

            modal.on('reveal:close', function () {
                if (!locked) {
                    lockModal();
                    modalBG.delay(options.animationspeed).fadeOut(options.animationspeed);
                    modal.animate({
                        "top": jQuery(document).scrollTop() - topOffset + 'px',
                        "opacity": 0
                    }, options.animationspeed / 2, function () {
                        modal.css({'top': topMeasure, 'opacity': 0, 'visibility': 'hidden'});
                        unlockModal();
                    });
                }
                modal.off('reveal:close');
            });


            modal.trigger('reveal:open')

            var closeButton = jQuery('.' + options.dismissmodalclass).on('click.modalEvent', function () {
                modal.trigger('reveal:close')
            });

            if (options.closeonbackgroundclick) {
                modalBG.css({"cursor": "pointer"})
                modalBG.on('click.modalEvent', function () {
                    modal.trigger('reveal:close')
                });
            }


            function unlockModal() {
                locked = false;
            }

            function lockModal() {
                locked = true;
            }

        });
    }
    /* 联系我们表单验证 */
    function contact_validation(sourceData) {

        //验证姓名为空
        jQuery('.formTips_username')[0].innerHTML = sourceData.name == '' ? '必填' : '';
        if (sourceData.email == '') {
            jQuery('.formTips_email')[0].innerHTML = '必填';
        } else if (sourceData.email != '' && !sourceData.email.match(/^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]+$/)) {
            jQuery('.formTips_email')[0].innerHTML = '格式错误';
        } else {
            jQuery('.formTips_email')[0].innerHTML = '';
        }
        jQuery('.formTips_type')[0].innerHTML = sourceData.questionType == '' ? '必填' : '';
        jQuery('.formTips_shop')[0].innerHTML = sourceData.store == '' ? '必填' : '';
        jQuery('.formTips_countury')[0].innerHTML = sourceData.country == '' ? '必填' : '';
        jQuery('.formTips_desc')[0].innerHTML = sourceData.desc == '' ? '必填' : '';

        //验证手机号码
        var mobile = sourceData.tel;
        var isMobile = /^(((13[0-9]{1})|(15[0-9]{1})|(18[0-9]{1})|(17[0-9]{1})|(14[0-9]{1}))+\d{8})$/;
        var isPhone = /^(?:(?:0\d{2,3})-)?(?:\d{7,8})(-(?:\d{3,}))?$/;

        var errorMsg = "格式错误";
        if (sourceData.tel == '') {
            jQuery('.formTips_tel')[0].innerHTML = '必填';
            return false;
        } else {
            jQuery('.formTips_tel')[0].innerHTML = '';
        }
        //如果为1开头则验证手机号码
        if (mobile.substring(0, 1) == 1) {
            if (!isMobile.exec(mobile) && mobile.length != 11) {
                jQuery('.formTips_tel')[0].innerHTML = errorMsg;
                return false;
            }
        }
        //如果为0开头则验证固定电话号码
        else if (mobile.substring(0, 1) == 0) {
            if (!isPhone.test(mobile)) {
                jQuery('.formTips_tel')[0].innerHTML = errorMsg;
                return false;
            }
        } else {
            jQuery('.formTips_tel')[0].innerHTML = errorMsg;
            return false;
        }
    }
    /* 处理立即验证按钮，默认是直接翻页下一步， 如果返回错误值，则停止翻页，弹出modal框 */
    function switchCondition(item) {
        if (item.attr('data-reveal-id') == 'alertValidRightNow') {
            if (jQuery('.btn_valid').attr('disabled') == undefined) {
                jQuery('.slide-group').animate({'top': '-1920px'});
            }
        } else {
            return false;
        }
    }
    jQuery(function () {
        jQuery('.q_1_true, .q_1_false, .q_2_true, .q_2_false').hide();
        jQuery('#q_1_true').click(function () {
            jQuery('.q_1_true').toggle();
            jQuery('.q_1_false').hide();
        });
        jQuery('#q_1_false').click(function () {
            jQuery('.q_1_false').toggle();
            jQuery('.q_1_true').hide();
        });
        jQuery('#q_2_true').click(function () {
            jQuery('.q_2_true').toggle();
            jQuery('.q_2_false').hide();
        });
        jQuery('#q_2_false').click(function () {
            jQuery('.q_2_false').toggle();
            jQuery('.q_2_true').hide();
        });
    });
</script>


