<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
<?php
    $page = Mage::app()->getFrontController()->getRequest()->getRouteName();
    $request = $this->getRequest();
    $module = $request->getModuleName();
?>
<div class="myAccountBox rewardPoints">
<!--	<h2>Reward Points</h2>-->
    <h2>奖励积分</h2>
    <table>
	<thead>
	    <tr>
<!--		<td>Points Available</td>-->
<!--		<td>Points Pending</td>-->
<!--		<td>Points Spent</td>-->
            <td>可用积分</td>
            <td>未到达积分</td>
            <td>已用积分</td>
	    </tr>
	</thead>
	<tbody>
	    <tr class="tableBgEven">
		<td><span class="yourPoints"><?php echo $this->getPointsCurrent(); ?></span></td>
		<td><?php echo $this->getPointsWaitingValidation(); ?></td>
		<td><?php echo $this->getPointsSpent(); ?></td>
	    </tr>
	</tbody>
	<?php if ($module == 'customer') : ?>
	    <tfoot>
		<tr>
		    <td colspan="3">
<!--			<a href="--><?php //echo $this->getUrl('rewardpoints/index/points/') ?><!--">View Reward Details</a>-->
            <a href="<?php echo $this->getUrl('rewardpoints/index/points/') ?>">查看积分详情</a>
		    </td>
		</tr>
	    </tfoot>
	<?php endif ?>
    </table>
<?php if ($module == 'customer') : ?>
</div>
<?php endif ?>