<style>
    #slideGroup {
        background: #000;
        text-align: center;
    }

    #slideGroup li img {
        width: 70%;
    }

    #slideGroup > ol > li, #slideGroup > ol > li.on {
        width: 12px;
        height: 12px;
        border-radius: 6px;
        margin: 0 4px;
        background: #fff;
    }

    #slideGroup > ol > li.on {
        background: #fdb803;
    }
</style>
<div class="checktf" style="-webkit-transform:translate3d(0,0,0);">
    <div id="slideGroup" class="box_swipe">
        <ul>
            <li><img id="img01" src="<?php echo $this->getSkinUrl("images/authentication/img01.png") ?>" /></li>
            <li><img id="img02" src="<?php echo $this->getSkinUrl("images/authentication/img02.png") ?>" /></li>
            <li><img id="img03" src="<?php echo $this->getSkinUrl("images/authentication/img03.png") ?>" /></li>
        </ul>
        <ol>
            <li class="on"></li>
            <li class=""></li>
            <li class=""></li>
        </ol>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/jquery.iosslider.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/swipe.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/jquery.SuperSlide.2.1.1.js"></script>
<script>
    jQuery(function(){
        new Swipe(document.getElementById('slideGroup'), {
            speed:1000,
            auto:0,
            callback: function(){
                var lis = jQuery(this.element).next("ol").children();
                lis.removeClass("on").eq(this.index).addClass("on");
            }
        });
    })
</script>
