<?php
$home_url = Mage::helper('core/url')->getHomeUrl();
$oid = '';
if(is_array($_GET)&&count($_GET)>0){
    if(isset($_GET["oid"])){
		$oid=$_GET["oid"];
    }
}

?>

<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('.confirmBtn').delegate(".ds_dialog_yes", "click", function () {
			searchTracking();
        });

		function searchTracking(){
			var orderId = jQuery("#orderId").val().trim();
			if (orderId != "") {
				jQuery.ajax({
					async: false,
					type: 'POST',
					url: '<?php echo $home_url;?>trackingSearch.php',
					data: {orderId: orderId},
					success: function (data) {
						jQuery('#checkBag').html(data);
					},
					error: function () {
					}
				});
			}
		}

		searchTracking();
    })
</script>
<div class="check_bg">
    <img src="<?php echo $this->getSkinUrl("images2019/checkBg.png") ?>" alt="">
</div>
<div id="my-account-wrapper">
    <div class="checkTitBox">
        <img src="<?php echo $this->getSkinUrl("images2019/checkTit.png") ?>" alt="">
    </div>

    <div id="my-confirm-login-wrapper" class="checkConfirm">
        <div class="my-account-content confirm-content">
            <form action="">
                <div class="confirmBox ms-fl">

                    <div class="infoInput"><input style="border: 1px solid #847450;color:#847450;" type="text" name="" id="orderId" placeholder="请输入官网或天猫订单号" value="<?php echo $oid;?>"></div>
                </div>
                <div class="confirmBtn ms-fl">
                    <i id="zy_check_ok" class="ds_dialog_yes" style="text-align:center;background:none;height:auto;color:#d4c8a0;font-style: normal;">查询</i>
                </div>
                <div class="clear"></div>
                <div id='checkBag' style="color:#fff"> </div>
            </form>
        </div>
    </div>
</div>

