<?php
$home_url = Mage::helper('core/url')->getHomeUrl();
?>

<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('.confirmBtn').delegate(".ds_dialog_yes", "click", function () {
            var orderId = jQuery("#orderId").val();
            var trackingResult = "";
            jQuery.ajax({
                async:false,
                type: 'POST',
                url: '<?php echo $home_url;?>trackingSearch.php',
                data: {orderId:orderId},
                success: function (data) {
                    jQuery('.confirmSn').html(data);
                },
                error: function () {
                }
            });
        });
    })
</script>

<div class="detail-back">
    <p><a href="<?php echo $home_url; ?>">返回首页</a></p>
</div>
<div id="my-account-wrapper">
    <h1>物流查询</h1>

    <div id="my-confirm-login-wrapper">
        <div class="my-account-content confirm-content">
            <form action="">
                <div class="confirmBox">
                    <p>订单号</p>

                    <div class="infoInput"><input type="text" name="" id="orderId"></div>
                </div>
                <div class="confirmBtn">
                    <i id="zy_check_ok" class="ds_dialog_yes">确认</i>
                </div>
                <div class="confirmSn">

                </div>
            </form>
        </div>
    </div>
</div>

