<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <title></title>
    <?php echo $this->getChildHtml('head') ?>

    <script>
        $(function(){
            setTimeout(function(){
                var sliderH = $('.spalding_index_slider img').height();
                //alert(sliderH);
                $('#focus').css("height",sliderH);
                //$('.footer').css("display","block")
            },100);

            $('.searchBtn').mouseover(function(){
                $(this).parents().find('.dropDown_search').slideDown();
            });

            $('.dropDownBg').on("click",function(){
                $(this).parent('.dropDown_search').slideUp();
            });
            $('.dropClose').on("click",function(){
                $(this).parent('.dropDown_search').slideUp();
            });

            //去除购物车列表中最后一行商品下划线
            $('.spListWrap>dl:last').css("border-bottom","none");

        });



    </script>


</head>
<!--style="background:#000;"-->
<body>
<div class="bodyBg"><img src=" <?php echo $this->getSkinUrl('images2019/20141210002.jpg');  ?>" alt=""></div>
<?php echo $this->getChildHtml('header') ?>
<!-- 主框架 s -->
<div style="height:110px; z-index:-2;"></div>
<?php echo $this->getChildHtml('content') ?>

<div style="width:100%;height:30px;"></div><!-- 底部充高 -->
<!-- 底部 bottom s -->
<?php echo $this->getChildHtml('footer') ?>
<!-- 底部 bottom e -->
</body>
</html>