<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <title>登录</title>
    <?php echo $this->getChildHtml('head') ?>

</head>
<!-- melone start 修改背景、字体颜色 -->
<body style="background:#fff; color:#83744d;">
<!--melone end 修改背景、字体颜色 -->
<div class="spaldingBg">
    <div class="spaldingBgImg"><!--<img src='<?php echo $this->getSkinUrl("images/20141209004.jpg") ?>'>--></div>
</div>
<?php //echo $this->getChildHtml('header') ?>
<div class="spaldingLogin">
    <div class="loginBox">
        <div class="loginBoxWrap">
            <!-- 顶部链接 -->
            <div class="header_nav">
                <div class="header_nav_funs header_nav_funs_login">
                    <a href="<?php echo $this->getUrl('customer/account/', array('_secure'=>true)) ?>">登录</a>&nbsp;|&nbsp;
                    <a href="<?php echo $this->getUrl('customer/account/create/', array('_secure'=>true)) ?>">注册</a>&nbsp;|&nbsp;
                    <a href="<?php echo $this->getUrl('customer/account/', array('_secure'=>true)) ?>">用户中心</a>&nbsp;|&nbsp;
                    <a href="<?php echo $this->getUrl('sales/order/history/', array('_secure'=>true)) ?>">我的订单</a>
                    <?php echo $this->getChildHtml('cart_sidebar_top') ?>
<!--                    <span>购物车<i><img src='--><?php //echo $this->getSkinUrl("images/20141208003.png") ?><!--'></i></span>-->
                </div>
            </div>

            <!-- 登录主框架 -->
            <div class="loginMain">
            <!-- melone start 修改images2019-->
                <div class="login_backHome" style="background: url(<?php echo $this->getSkinUrl("images2019/20141209011.png") ?>) left center no-repeat;"><a href="<?php echo $this->getUrl('') ?>">返回首页</a></div>
                <div class="loginWel"><img src='<?php echo $this->getSkinUrl("images2019/20141209012.png") ?>'></div>
            <!-- melone end 修改images2019-->
                <?php echo $this->getChildHtml('content') ?>
            </div>

        </div>
        <div class="clear"></div>
        <div class="loginBottom">
            <p>欢迎访问斯伯丁中国！斯伯丁官方商城</p>
            <p>©2014 SPALDING CHINA 备案编号：沪ICP备14046632号-1</p>
        </div>
    </div>
</div>
</body>
</html>