<?php $this->initView(); ?>
<?php $_product = $this->getProduct(); ?>
<?php
$productImageHelper = Mage::helper('product');
?>
<div class="cusMadeBox cusMadeCen">
    <div id="playimages" class="play">
        <?php if ($this->getTypeP1() == 1 && $this->getTypeP2() == 1): ?>
            <!-- 第一套 s -->
            <!-- 图片-图片 -->
            <ul class="big_pic">
                <div class="imgBox imgPag_1 imgPag_1_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P1() ?>" alt="" /></div>
                <div class="imgBox imgPag_2 imgPag_2_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_tt/1.png") ?>" alt="" /></div>
            </ul>
            <!-- 第一套 e -->


        <?php elseif($this->getTypeP1() == 2 && $this->getTypeP2() == 2): ?>
            <!-- 第二套 s -->
            <!-- 文字-文字 -->
            <ul class="big_pic">
                <!-- P1  -->
                <?php if($this->getContent3P1() == 4): ?>
                    <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "  <?php echo $this->getP1Font() ?> ><?php echo $this->getContent1P1() ?></div>
                    <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> towLine_view_1"  <?php echo $this->getP1Font() ?> ><?php echo $this->getContent2P1() ?></div>
                <?php else: ?>
                    <div class="textBox textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> " <?php echo $this->getP1Font() ?> ><?php echo $this->getContent1P1() ?></div>
                <?php endif; ?>
                <!-- P2  -->
                <?php if($this->getContent3P2() == 4): ?>
                    <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>" <?php echo $this->getP2Font() ?> ><?php echo $this->getContent1P2() ?></div>
                    <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?> towLine_view_2" <?php echo $this->getP2Font() ?> ><?php echo $this->getContent2P2() ?></div>
                <?php else: ?>
                    <div class="textBox textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>" <?php echo $this->getP2Font() ?> ><?php echo $this->getContent1P2() ?></div>
                <?php endif; ?>
            </ul>
            <!-- 第二套 e -->

        <?php elseif($this->getTypeP1() == 1 && $this->getTypeP2() == 2): ?>

            <!-- 第三套 s -->
            <!-- 图片-文字 -->
            <ul class="big_pic">
                <!-- P1  -->
                <div class="imgBox imgPag_1 imgPag_1_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P1() ?>" alt="" /></div>
                <!-- P2  -->
                <?php if($this->getContent3P2() == 4): ?>
                    <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>" <?php echo $this->getP2Font() ?>><?php echo $this->getContent1P2() ?></div>
                    <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?> towLine_view_2"  <?php echo $this->getP2Font() ?>><?php echo $this->getContent2P2() ?></div>
                <?php else: ?>
                    <div class="textBox textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>" <?php echo $this->getP2Font() ?>><?php echo $this->getContent1P2() ?></div>
                <?php endif; ?>
                <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_tz/1.png") ?>" alt="" /></div>
            </ul>
            <!-- 第三套 e -->


        <?php elseif($this->getTypeP1() == 2 && $this->getTypeP2() == 1): ?>
            <!-- 第四套 s -->
            <!-- 文字-图片 -->
            <ul class="big_pic">
                <!-- P1  -->
                <?php if($this->getContent3P1() == 4): ?>
                    <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "  <?php echo $this->getP1Font() ?>><?php echo $this->getContent1P1() ?></div>
                    <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> towLine_view_1"  <?php echo $this->getP1Font() ?>><?php echo $this->getContent2P1() ?></div>
                <?php else: ?>
                    <div class="textBox textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "  <?php echo $this->getP1Font() ?>><?php echo $this->getContent1P1() ?></div>
                <?php endif; ?>
                <!-- P2  -->
                <div class="imgBox imgPag_2 imgPag_2_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_zt/1.png") ?>" alt="" /></div>
            </ul>
            <!-- 第四套 e -->


        <?php elseif($this->getTypeP1() == 1 && ($this->getTypeP2() != 1 && $this->getTypeP2() != 2)): ?>
            <!-- 第五套 s -->
            <!-- 图片-空 -->
            <ul class="big_pic">
                <div class="imgBox imgPag_1 imgPag_1_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P1() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_tk/1.png") ?>" alt="" /></div>
            </ul>


            <!-- 第五套 e -->


        <?php elseif($this->getTypeP1() == 2 && ($this->getTypeP2() != 1 && $this->getTypeP2() != 2)): ?>
            <!-- 第六套 s -->
            <!-- 文字-空 -->
            <ul class="big_pic">
                <?php if($this->getContent3P1() == 4): ?>
                    <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "  <?php echo $this->getP1Font() ?>><?php echo $this->getContent1P1() ?></div>
                    <div class="textBox textBox_2 textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> towLine_view_1"  <?php echo $this->getP1Font() ?>><?php echo $this->getContent2P1() ?></div>
                <?php else: ?>
                    <div class="textBox textPag_1 <?php echo $this->getSizeClassP1() ?> textPag_1_<?php echo $_i ?> "  <?php echo $this->getP1Font() ?>><?php echo $this->getContent1P1() ?></div>
                <?php endif; ?>
                <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_zk/1.png") ?>" alt="" /></div>
            </ul>
            <!-- 第六套 e -->


        <?php elseif(($this->getTypeP1() != 1 && $this->getTypeP1() != 2) && $this->getTypeP2() == 1): ?>
            <!-- 第七套 s -->
            <!-- 空-图片 -->
            <ul class="big_pic">
                <div class="imgBox imgPag_2 imgPag_2_<?php echo $_i ?>"><img src="<?php echo $this->getContent1P2() ?>" alt="" /></div>
                <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_kt/1.png") ?>" alt="" /></div>
            </ul>



            <!-- 第七套 e -->


        <?php elseif(($this->getTypeP1() != 1 && $this->getTypeP1() != 2) && $this->getTypeP2() == 2): ?>
            <!-- 第八套 s -->
            <!-- 空-文字 -->
            <ul class="big_pic">
                <?php if($this->getContent3P2() == 4): ?>
                    <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>"  <?php echo $this->getP2Font() ?>><?php echo $this->getContent1P2() ?></div>
                    <div class="textBox textBox_2 textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?> towLine_view_2"  <?php echo $this->getP2Font() ?>><?php echo $this->getContent2P2() ?></div>
                <?php else: ?>
                    <div class="textBox textPag_2 <?php echo $this->getSizeClassP2() ?> textPag_2_<?php echo $_i ?>"  <?php echo $this->getP2Font() ?>><?php echo $this->getContent1P2() ?></div>
                <?php endif; ?>
                <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_kz/".substr(strval($_i+100),1,3).".png") ?>" alt="" /></div>
            </ul>



            <!-- 第八套 e -->


        <?php else: ?>
            <!-- 第九套 s -->
            <!-- 空-空 -->
            <ul class="big_pic">
                <div class="imgBox imgBall"><img src="<?php echo $productImageHelper->getCustomMadeImage($_product->getSku()."/imgBall_kk/1.png") ?>" alt="" /></div>
            </ul>
            <!-- 第九套 e -->
        <?php endif; ?>

    </div>
    <div class="viewBack viewMade" id="exitView">
        <div class="prev"></div>
        <div class="next"></div>
        <div class="prev_n_top"></div>
        <div class="next_z_top"></div>
        <div class="prev_n arrow_btn"></div>
        <div class="next_z arrow_btn"></div>
        <button type="button"><img src="<?php  echo $productImageHelper->getCustomMadeImage("viewMadeBack.png") ?>" alt=""></button>
    </div>
</div>