
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mobile_cs_return_to_menu')->toHtml(); ?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div id="my-account-wrapper">
	<h1>Track Your Order</h1>
	<div id="my-account-login-wrapper">
		<div class="my-account-content" style="border: none !important">

			<form id="orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
				<div class="logInInfoBox">
				<p class="boldText yellowText">Please be aware that order status may not be available within the first 12 hours of placing an order.</p>
				</div>
				<div class="logInInfoBox">
				<table>
					<tbody>
					<tr>
						<td class="infoLabel"><label for="oar_order_id" class="required"><span class="rStar">*</span>Order ID</label></td>
					</tr>
					<tr>
						<td class="infoInput"><input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id"/></td>
					</tr>
					<tr>
						<td class="infoLabel"><label for="oar_billing_lastname" class="required"><span class="rStar">*</span>Billing Last Name</label></td>
					</tr>
					<tr>
						<td class="infoInput"><input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname"/></td>
					</tr>

					<input type="hidden" name="oar_type" id="quick_search_type_id" value="email">
					<input type="hidden" id="oar_zip" name="oar_zip"/>

					<tr id="oar-email">
						<td class="infoLabel"><label for="oar_email" class="required"><span class="rStar">*</span>Email Address</label></td>
					</tr>
					<tr>
						<td class="infoInput"><input type="text" class="input-text validate-email required-entry" id="oar_email" name="oar_email"/></td>
					</tr>
					</tbody>
				</table>
				</div>
				<div class="serviceTextWrap">
				<p>If you still have questions, please call Customer Service at <span class="greyText boldText">1-866-339-7463. Representatives are available Mon-Fri 8am-5pm PST, Sat 8am-3pm PST, Sunday (Closed)</span>.</p>
				</div>
				<div class="logInInfoBox">
				<table class="logInInfoBtn">
					<tr>
					<td class="submitBtn continue">
						<button type="submit" title="Continue" class="button" onClick="return validateForm('#orders_and_returns_form')">Continue</button>
					</td>
					</tr>
				</table>
				<div class="clearfloats"></div>
				</div>
				<div class="logInInfoBox">
				<p class="required">* Required Fields</p>
				</div>
			</form>
		</div>
	</div>
</div>
