<?php
list($appId,$timestamp,$noncestr,$signature,$currentUrl) = $this->getVar();
$title = "微信活动";
$desc = "微信活动";
$shareimageurl ="http://images.spaldingchina.com.cn/skin/frontend/default/spalding/images/20141208001.jpg";

$uid = 778899;
$actId =  998877;
?>


<!-- 请输入手机号:<input id="telephone" type="text" />
<input id="btnSendCode" type="button" value="发送验证码" onclick="sendMessage()" /><br />
请输入验证码:<input id="captcha" type="text">
<input id="btnCheckCode" type="button" value="验证" onclick="checkMessage()" /> -->
<style>
    html{
        position: relative;
        width: 100%;
        height: 100%;
        overflow: hidden;
    }
    body{
        position: relative;
        width:100%;
        height: 100%;
        background: url(<?php echo $this->getSkinUrl("images/weixin/weix_bg1.jpg"); ?>) left top no-repeat;
        background-size: 100% 100%;
        overflow: hidden;
    }
    #page{
        height:100%;
    }
    .content-wrapper{
        margin:0 auto;
        height:100%;
        position: relative;
    }
</style>
<div class="popPhone">
    <div class="popPhoneWrap">
        <div class="popPhoneClose clearfix">
            <img src="<?php echo $this->getSkinUrl("images/weixin/popClose.png"); ?>" alt="">
        </div>
        <div class="popPhoneBox">
            <h2>领取优惠券</h2>
            <p>恭喜你点亮第一个球，获得斯伯丁官方商城<font style="color:#fc0">10元优惠券</font>一张请输入你的手机号以领取：</p>
            <div class="popPhoneInp">
                <div class="phoneInpNum">
                    <span class="telNum"><input type="text" placeholder="请输入手机号码" class="telWrap" ></span>
                    <span class="clearTel">x</span>
                    <span class="sendCd">
                        <button>发送验证码</button>
                    </span>
                </div>
                <div class="phoneInpCd">
                    <input type="text" placeholder="请输入收到的验证码">
                </div>
            </div>
            <div class="popPhoneBtn">
                <button>验证手机号</button>
            </div>
        </div>
    </div>
</div>
<div class="container">

    <div class="page page0 cur">
        <div class="wxWrap">
        <!-- <div class="wxWrapBg"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/weix_bg1.jpg" alt=""></div> -->
            <div class="wxTit"><img src="<?php echo $this->getSkinUrl("images/weixin/wxTitle.png"); ?>" alt=""></div>


            <div class="wxBalls">
                <div class="wxBall wxBall_1">
                    <span class="wxBallGy wxBallGys"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/wxBallGy.png" alt=""></span>
                    <span class="wxBallCon"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/ball_1.png" alt=""></span>
                </div>

                <div class="wxBall wxBall_2">
                    <span class="wxBallGy wxBallGys"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/wxBallGy.png" alt=""></span>
                    <span class="wxBallCon"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/ball_2.png" alt=""></span>
                </div>

                <div class="wxBall wxBall_3">
                    <span class="wxBallGy"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/wxBallGy.png" alt=""></span>
                    <span class="wxBallCon"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/ball_3.png" alt=""></span>
                </div>

                <div class="wxBall wxBall_4">
                    <span class="wxBallGy wxBallGys"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/wxBallGy.png" alt=""></span>
                    <span class="wxBallCon"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/ball_4.png" alt=""></span>
                </div>

                <div class="wxBall wxBall_5">
                    <span class="wxBallGy wxBallGys"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/wxBallGy.png" alt=""></span>
                    <span class="wxBallCon"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/ball_5.png" alt=""></span>
                </div>
            </div>
            <div class="ruls"><img src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/images/weixin/rules.png" alt=""></div>
        </div>
    </div>
    <div class="page page1">
        <h1>游戏规则</h1>
        <h2>活动日期：2015年6月17日~2015年7月31日</h2>
        <ul>
            <li class="clearfix">
                <span class="rulNum">1、</span>
                <span class="rulTex">在斯伯丁官方商城（Spaldingchina.com.cn）下单并分享至微信朋友圈或发送好友和群，即可获赠斯伯丁专业篮球袜一双</span>
            </li>
            <li class="clearfix">
                <span class="rulNum">2、</span>
                <span class="rulTex">好友互动可为你点亮一颗篮球（一共五颗篮球可以被点亮），你的好友将获得斯伯丁官方商城10元优惠券（满100元可以使用）</span>
            </li>
            <li class="clearfix">
                <span class="rulNum">3、</span>
                <span class="rulTex">5颗篮球全部被点亮之后，你可获得官方商城10元无门槛优惠券。</span>
            </li>
            <li class="clearfix">
                <span class="rulNum">4、</span>
                <span class="rulTex">所有优惠券有效期为自发放日起的30天内，一笔订单只能使用一张优惠券，券不可重叠使用。</span>
            </li>
            <li class="clearfix">
                <span class="rulNum">5、</span>
                <span class="rulTex">未在斯伯丁官方商城购物，您也可以转发本次活动，但是无法获得袜子和无门槛优惠券的奖励。</span>
            </li>
            <li class="clearfix">
                <span class="rulNum">6、</span>
                <span class="rulTex">本次活动最终解释权归斯伯丁中国所有。</span>
            </li>
        </ul>
    </div>



</div>


<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript"></script>
<script>

    function sendMessage() {

        var telephone = document.getElementById("telephone").value;
        jQuery.ajax({
            type: 'POST',
            url: '<?php echo $this->getUrl('weixinevent/index/sendCaptcha') ?>',
            data: {telephone: telephone},
            success: function (data) {
                alert(data);
            },
            //  dataType: "json",
            error: function () {
                alert('error');
            },
            complete:function(){
                //document.getElementById("btnSendCode").disabled = true;
            }
        });

    }

    function checkMessage() {
        var inputCaptcha = document.getElementById("captcha").value;
        var telephone = document.getElementById("telephone").value;
        var clickOrder = 3;

        jQuery.ajax({
            type: 'POST',
            url: '<?php echo $this->getUrl('weixinevent/index/checkCaptcha') ?>',
            data: {inputCaptcha: inputCaptcha,telephone: telephone,clickOrder: clickOrder},
            success: function (data) {
                if(jQuery.trim(data) == "Success") {
                    alert("验证成功");
                }else{
                    alert("验证失败");
                }
            },
            error: function () {

            }
        });
    }

    function sharePromotion() {
        jQuery.ajax({
            type: 'POST',
            url: '<?php echo $this->getUrl('weixinevent/index/updatePromotionData') ?>',
            success: function (data) {

            },
            error: function () {

            }
        });
    }
    wx.config({
        debug: false, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
        appId: '<?php echo $appId  ?>', // 必填，公众号的唯一标识
        timestamp:  '<?php echo $timestamp  ?>', // 必填，生成签名的时间戳
        nonceStr: '<?php echo $noncestr  ?>', // 必填，生成签名的随机串
        signature: '<?php echo $signature  ?>',// 必填，签名，见附录1
        jsApiList: ['checkJsApi',
            'onMenuShareTimeline',
            'onMenuShareAppMessage',
            'onMenuShareQQ',
            'onMenuShareWeibo',
            'hideMenuItems',
            'showMenuItems',
            'hideAllNonBaseMenuItem',
            'showAllNonBaseMenuItem',
            'translateVoice',
            'startRecord',
            'stopRecord',
            'onRecordEnd',
            'playVoice',
            'pauseVoice',
            'stopVoice',
            'uploadVoice',
            'downloadVoice',
            'chooseImage',
            'previewImage',
            'uploadImage',
            'downloadImage',
            'getNetworkType',
            'openLocation',
            'getLocation',
            'hideOptionMenu',
            'showOptionMenu',
            'closeWindow',
            'scanQRCode',
            'chooseWXPay',
            'openProductSpecificView',
            'addCard',
            'chooseCard',
            'openCard'] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
    });
    wx.ready(function () {
        // 1 判断当前版本是否支持指定 JS 接口，支持批量判断
        wx.checkJsApi({
            jsApiList: [
                'onMenuShareTimeline',
                'getNetworkType',
                'hideMenuItems',
                'previewImage'
            ],
            success: function (res) {
                //alert(JSON.stringify(res));
            }
        });

        // 2. 分享接口

        // 2.2 监听“分享到朋友圈”按钮点击、自定义分享内容及分享结果接口
        wx.onMenuShareTimeline({
            title: '<?php echo $title;  ?>',
            link: "<?php echo $currentUrl;  ?>",
            imgUrl: "<?php echo $shareimageurl;  ?>",
            trigger: function (res) {
                //alert('用户点击分享到朋友圈');
            },
            success: function (res) {
                //如果分享成功
                sharePromotion();
                alert(1);

            },
            cancel: function (res) {
                //alert('已取消');
            },
            fail: function (res) {
                //alert(JSON.stringify(res));
            }
        });

        wx.onMenuShareAppMessage({
            title: '<?php echo $title;  ?>',
            desc:  '<?php echo $desc;  ?>',
            link: '<?php echo $currentUrl;  ?>',
            imgUrl: '<?php echo $shareimageurl;  ?>',
            trigger: function (res) {
                alert('用户点击发送给朋友');
            },
            success: function (res) {
                //如果分享成功
                alert(22);
                sharePromotion();
                alert(2);
            },
            cancel: function (res) {
                alert('已取消');
            },
            fail: function (res) {
                alert(JSON.stringify(res));
            }
        });

    });
    wx.error(function (res) {
        alert(res.errMsg);
    });

    //   jQuery(function(){
    //        alert(1);
    //    });
</script>

<script type="text/javascript" src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="../../../../../../../../spalding_mobile/skin/frontend/default/mobile/js/jquery.touchSwipe.min.js"></script>
<script type="text/javascript">

    jQuery(document).ready(
        //滑动整屏滚动
        function() {
            var nowpage = 0;
            //给最大的盒子增加事件监听
            jQuery(".container").swipe(
                {
                    swipe:function(event, direction, distance, duration, fingerCount) {
                         if(direction == "up"){
                            nowpage = nowpage + 1;
                         }else if(direction == "down"){
                            nowpage = nowpage - 1;
                         }

                         if(nowpage > 1){
                            nowpage = 1;
                         }

                         if(nowpage < 0){
                            nowpage = 0;
                         }

                        jQuery(".container").animate({"top":nowpage * -100 + "%"},400);

                        jQuery(".page").eq(nowpage).addClass("cur").siblings().removeClass("cur");
                    }
                });
        }


    );

    jQuery(function(){
        //点亮球
        jQuery(".wxBall").on("touchstart",function(){
            var _wxBallGy = jQuery(".wxBallGys");
            var _wxBallGyLen = _wxBallGy.length;
            if(_wxBallGyLen>0){
                jQuery(this).children(".wxBallGys").remove();
                jQuery(this).parents().find(".popPhone").show();
            }else{
                jQuery(this).off("touchstart");
                //alert("已完全点亮");
            }

        });

        //关闭手机验证
        jQuery(".popPhoneClose").on("touchstart",function(){
            jQuery(this).parents(".popPhone").hide();
        });

        //清除手机号码
        jQuery(".clearTel").on("click",function(){
            jQuery(this).siblings(".telNum").find(":text").val("").focus();
        });

     });

</script>
