<?php
list($appId,$timestamp,$noncestr,$signature,$currentUrl) = $this->getVar();
$title = "微信活动";
$desc = "微信活动";
$shareimageurl ="http://images.spaldingchina.com.cn/skin/frontend/default/spalding/images/20141208001.jpg";
?>

<input id="a1" type="text" value="" " />
<input id="a2" type="button" value="发送验证码" onclick="sendMessage()" /></p>
<input id="a1" type="text" value="" " /></p>
<input id="a2" type="button" value="验证" onclick="sendMessage()" /></p>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript"></script>
<script>
    wx.config({
        debug: false, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
        appId: '<?php echo $appId  ?>', // 必填，公众号的唯一标识
        timestamp:  '<?php echo $timestamp  ?>', // 必填，生成签名的时间戳
        nonceStr: '<?php echo $noncestr  ?>', // 必填，生成签名的随机串
        signature: '<?php echo $signature  ?>',// 必填，签名，见附录1
        jsApiList: ['checkJsApi',
            'onMenuShareTimeline',
            'onMenuShareAppMessage',
            'onMenuShareQQ',
            'onMenuShareWeibo',
            'hideMenuItems',
            'showMenuItems',
            'hideAllNonBaseMenuItem',
            'showAllNonBaseMenuItem',
            'translateVoice',
            'startRecord',
            'stopRecord',
            'onRecordEnd',
            'playVoice',
            'pauseVoice',
            'stopVoice',
            'uploadVoice',
            'downloadVoice',
            'chooseImage',
            'previewImage',
            'uploadImage',
            'downloadImage',
            'getNetworkType',
            'openLocation',
            'getLocation',
            'hideOptionMenu',
            'showOptionMenu',
            'closeWindow',
            'scanQRCode',
            'chooseWXPay',
            'openProductSpecificView',
            'addCard',
            'chooseCard',
            'openCard'] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
    });
    wx.ready(function () {
        // 1 判断当前版本是否支持指定 JS 接口，支持批量判断
        wx.checkJsApi({
            jsApiList: [
                'onMenuShareTimeline',
                'getNetworkType',
                'hideMenuItems',
                'previewImage'
            ],
            success: function (res) {
                //alert(JSON.stringify(res));
            }
        });

        // 2. 分享接口

        // 2.2 监听“分享到朋友圈”按钮点击、自定义分享内容及分享结果接口
        wx.onMenuShareTimeline({
            title: '<?php echo $title;  ?>',
            link: "<?php echo $currentUrl;  ?>",
            imgUrl: "<?php echo $shareimageurl;  ?>",
            trigger: function (res) {
                //alert('用户点击分享到朋友圈');
            },
            success: function (res) {
                //如果分享成功
                alert(1);

            },
            cancel: function (res) {
                //alert('已取消');
            },
            fail: function (res) {
                //alert(JSON.stringify(res));
            }
        });

        wx.onMenuShareAppMessage({
            title: '<?php echo $title;  ?>',
            desc:  '<?php echo $desc;  ?>',
            link: '<?php echo $currentUrl;  ?>',
            imgUrl: '<?php echo $shareimageurl;  ?>',
            trigger: function (res) {
                //alert('用户点击发送给朋友');
            },
            success: function (res) {
                //如果分享成功 
                alert(2);
            },
            cancel: function (res) {
                //alert('已取消');
            },
            fail: function (res) {
                //alert(JSON.stringify(res));
            }
        });

    });
    wx.error(function (res) {
       // alert(res.errMsg);
    });

//   jQuery(function(){
//        alert(1);
//    });
</script>