
<?php

$alipay = Mage::getModel('alipay/payment');
?>

<script type="text/javascript">
jQuery.noConflict();
</script>
<?php


$orderId = (int) $this->getRequest()->getParam('order_id');
if (!$orderId) {
    $session = Mage::getSingleton('checkout/session');
    $_order = Mage::getModel('sales/order');

    $_order->loadByIncrementId($session->getLastRealOrderId());
}else{


    $_order =Mage::getModel('sales/order')->load($orderId);

    $order_cid=$_order->getCustomerId();
    $current_cid=0;
    if(Mage::helper('customer')->getCustomer()){
        $current_cid=Mage::helper('customer')->getCustomer()->getId();
    }

    if ($current_cid!=$order_cid)
    {
        echo '订单错误，请联系我们';
        exit();
    }
}
if (!$_order->getId())
{
    echo '订单错误，请联系我们';
    exit();
}
$warnImageSrc =$this->getSkinUrl( "images/warn.png");
?>


<?php
$_customError = false;
$_items = $_order->getItemsCollection();
$_flag = false;
$isCustomClothes = false;
foreach ($_items as $_item){
    if (!($_item->getParentItem())) {
        $_product = $_item->getProduct();

        if(Mage::getModel('customclothes/customClothes')->checkCustomClothesByProdcut($_product)){
        	$isCustomClothes = true;
        }

        if ($_product->getIsCustom()) {
            $_flag = true;
            $customOrder = Mage::getModel('custommade/info')->loadByIncrementId($_order->getRealOrderId());
            $customOrderId = $customOrder->getId();
            if (!$customOrderId) {
                $_customError = true;
            }
        }
    }
}
?>
<style>
    .payCustomPopUp{position:absolute; z-index:999999;background: rgba(0,0,0,.9);width:100%;height:100%;left:0; top:0; padding:10px;overflow: hidden;}
    .payPopUpCons{
        color:#f4b201;
        font-size: 12px;
    }
    .payPopUpCons h2{
        font-size: 13px;
        font-weight: bold;
        text-align: center;
    }
    .payPopUpCons p{
        line-height: 2em;
        height:auto;
        margin:0;
    }
    .payPopUpConf{
        text-align: center;
        background: #f4b201;
        color:#000;
        font-size: 13px;
        font-weight: bold;
        border-radius: 4px;
        cursor: pointer;
        margin: 10px auto 5px;
        padding: 5px 0;
        width: 100px;
    }
    .payPopBack{
        font-size: 12px;
        text-align: center;
        padding-top: 5px;
    }
    .payPopBack a{
        color:#fff;
        text-decoration: underline;
    }
    .payPopBack a:hover{
        color:#f4b201;
    }
</style>
<script>
    jQuery(function(){
        jQuery(".payPopUpConf").click(function(){
            jQuery(this).parent(".payCustomPopUp").css("display","none");
        });
    });
</script>
<div class="shortcut_wrapper shorturt_mobile" style="width: 100%;">
    <div class="shortcut_price">
        <p class="price">支付金额：<span class="red"><?php echo $this->helper('checkout')->formatPrice($_order->getGrandTotal()) ?> </span></span></p>
        <p><span>类型：<span id="lblType">订单</span></span><span>编号：<span id="lblNo"><?php echo ($_order->getRealOrderId()) ?> </span></span></p>
        <?php if ($_flag): ?>
            <?php $customMsg = Mage::getModel('custommade/info')->loadByIncrementId($_order->getRealOrderId()) ?>
            <div style="color:#f4b201;padding:10px;font-size:12px;border:1px solid #999;margin:0 10px;">
                定制一：
                <?php
                if($customMsg->getTypeP1() == 1):
                    ?>
                    <a target="_blank" href="<?php echo $customMsg->getMsg3P1();?>">浏览图片</a>
                <?php
                    elseif ($customMsg->getTypeP1() == 4):
                 ?>
                    <img src="<?php echo $this->getSkinUrl('imagesEmblem/'.$customMsg->getMsg1P1().'.png'); ?>" style="height: 50px;vertical-align: middle;" alt="">
                    <?php
                else:
                    if(trim($customMsg->getMsg4P1()) != ''):
                        echo Mage::getModel('custommade/info')->getMsg4PositionResult($customMsg);
                    endif;
                    if(trim($customMsg->getMsg3P1()) != ''):
                        echo '， ' . Mage::getModel('custommade/info')->getMsg4SizeResult($customMsg).'， ';
                    endif;
                    if ($customMsg->getMsg3P1() == 4):
                        echo '第一行：' . $customMsg->getMsg1P1();
                        ?>
                        <br />
                        <?php
                        echo '第二行：' . $customMsg->getMsg2P1();
                    else:
                        echo $customMsg->getMsg1P1();
                    endif;
                endif;
                ?>
            </div>
            <div class="productsListRow" style="color:#f4b201;padding:10px;font-size:12px;border:1px solid #999;border-top:0;margin:0 10px;">
                定制二：
                <?php
                if($customMsg->getTypeP2() == 1):
                    ?>
                    <a target="_blank" href="<?php echo $customMsg->getMsg3P2();?>">浏览图片</a>
                <?php
                    elseif ($customMsg->getTypeP2() == 4):
                 ?>
                    <img src="<?php echo $this->getSkinUrl('imagesEmblem/'.$customMsg->getMsg1P2().'.png'); ?>" style="height: 50px;vertical-align: middle;" alt="">
                 <?php
                else:
                    if(trim($customMsg->getMsg4P2()) != ''):
                        echo Mage::getModel('custommade/info')->getMsg4PositionResult($customMsg,2);
                    endif;
                    if(trim($customMsg->getMsg3P2()) != ''):
                        echo '， '.Mage::getModel('custommade/info')->getMsg4SizeResult($customMsg,2).'， ';
                    endif;
                    if ($customMsg->getMsg3P2() == 4):
                        echo '第一行：' . $customMsg->getMsg1P2();
                        ?><br />
                        <?php
                        echo '第二行：' . $customMsg->getMsg2P2();
                    else:
                        echo $customMsg->getMsg1P2();
                    endif;
                endif;
                ?>
            </div>
            <p style="width: 100%;"><span>注：定制产品区别于普通产品，订单审核、生产约需25个工作日左右后发出，若时间周期有冲突的顾客，敬请见谅。</span></p>
        <?php endif; ?>

        <?php if ($isCustomClothes): ?>
        <style>
            .madeCens{
                color:#fff;
                font-size: 14px;
                margin:0 10px;
            }
            .madeCens th, .madeCens td{
                border:1px solid #666;
                padding:5px;

            }
            .madeCens th{
                font-weight: bold;
                background: #333;
            }
            .madeCens td{
                color:#f4b201;
            }
            .madeCens table{width:100%}
        </style>
        <div  class="madeCens">
        <table>
            <tr>
                <th>定制内容</th>
            </tr>
              <?php
        		$customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
            	$dataRow = Mage::getModel('customclothes/order')->loadByIncrementId($_order->getRealOrderId());
        	?>
            <tr>
                <td>
                   	<a target="_blank" href="<?php echo $dataRow->result_image;?>">定制浏览</a>
                </td>
            </tr>
        </table>
        </div>
         <p style="padding:10px 50px 0 10px "><span>注：定制产品区别于普通产品，订单审核、生产约需25个工作日左右后发出，若时间周期有冲突的顾客，敬请见谅。</span></p>
        <?php endif; ?>
    </div>

    <?php
    //需要判断订单状态 如果已经付款成功，直接显示付款成功的提示
    if($_order->getStatus() == 'alipay_wait_seller_send_goods'){
        //已经付款成功
        echo '<div class="box">订单已经付款成功</div>';
    }else if($_order->getStatus() == 'canceled'){
        //已经付款成功
        echo '<div class="box">订单已经取消</div>';
    }else{
    ?>
    <div class="box" style="position:relative">
        <?php if ($_flag||$isCustomClothes): ?>
            <div class="payCustomPopUp">
                <div class="payPopUpCons">
                    <h2>温馨提示</h2>
                    <p>1，由于是个性化定制商品，订单付款后概不退换。</p>
                    <p>2，审核后的订单预计将在25个工作日左右生产完成并发货。</p>
<!--                    <p>3，定制内容易磨损，建议将定制球作为观赏收藏使用。</p>-->
                </div>
                <div class="payPopUpConf">确认</div>
                <!--<div class="payPopUpConf">确认</div>-->
                <div class="payPopBack"><a href="<?php echo $this->getUrl('sales/order/history/') ?>">暂不付款</a></div>
            </div>
        <?php endif; ?>
<?php

$weixinImageSrc = $this->getSkinUrl( "images/pay_weixin.gif");
$alipayImageSrc = $this->getSkinUrl( "images/bankico/alipay.jpg");
$alipayQrImageSrc = $this->getSkinUrl( "images/bankico/alipay_qr.jpg");
//判断当前浏览器是否为微信
$weixinPay = false;
$agent = $_SERVER['HTTP_USER_AGENT'];
if (strpos($agent, "MicroMessenger")) {
    $weixinPay = true;
}
?>
        <p>点击选择支付平台前往付款：</p>
        <ul class="clearfix">
        <?php if ($weixinPay): ?>
            <li>
                <input type="radio"  name="bank" checked="checked" id="payment_4" onclick="setBank('<?php echo $this->getUrl('weixinpay/payment/wappay')?>','weixin_pay','<?php echo $_order->getId();?>')">
                <label for="payment_4">
                    <img  id="payimg4" alt="微信支付" title="微信支付" src="<?php echo $weixinImageSrc; ?>">
                </label>
            </li>
        <?php else: ?>
            <li>
                <input type="radio"  name="bank" checked="checked" id="payment_2" onclick="setBank('<?php echo $this->getUrl('alipay/payment/wapredirect')?>','alipay_mobile','<?php echo $_order->getId();?>')">
                <label for="payment_2">
                    <img  id="payimg2" alt="支付宝" title="支付宝" src="<?php echo $alipayImageSrc; ?>">
                </label>
            </li>
        <?php endif;?>
        </ul>

        <div style="text-align: left">
            <a id="submitbutton" class="paymentBtn" target="_blank">我要付款</a>

        </div>
    </div>
    <?php
    }
    ?>
  <div class="bottom_hint">
    <div><a href="<?php echo $this->getUrl('sales/order/view',array('order_id'=>$_order->getId())); ?>" target="_blank">查看订单详情&gt;&gt;</a></div>
    <div class="title">付款遇到问题：</div>
    <!--<p>联系我们 <span class="gray"> 客服帮助您解决支付过程中遇到的困难 <a href="<?php /*echo $this->getUrl('contacts'); */?>" target="_blank" >客服中心</a> </span></p>-->
    <div style="margin-top:15px;"><a href="http://help.alipay.com/lab/index.htm" target="_blank">支付宝帮助中心&nbsp;&gt;&gt;</a></div>
  </div>
</div>

<div class="popup-wrap popup-orderEnd" style="display:none;" id="go_pay_window">
    <div class="popup-title">
        <h3>温馨提示</h3>
        <a class="btn-popup-close" href="javascript:window_close();"></a>
    </div>
    <div class="tit"></div>
    <div class="popup-cont">
        <div class="msg-tit">
            <i></i>
            请在新打开的页面中完成付款
        </div>
        <div class="msg-text">
            付款完成前请不要关闭此窗口<br>完成付款后请点击下面按钮
        </div>
        <div class="msg-btns">
            <input type="button" value="完成付款" class="actbtn success" onclick="setLocation('<?php echo $this->getUrl('sales/order/view',array('order_id'=>$_order->getId())); ?>')">
            <input type="button" value="付款遇到问题" class="actbtn fail" onclick="setLocation('<?php echo $this->getUrl('contacts'); ?>');">
        </div>
        <div class="bgpay">
            <i></i>
            <a onclick="javascript:window_close();" href="javascript:void(0)">返回选择其它支付方式</a>
        </div>
    </div>
</div>
<script>
    jQuery(document).ready(function(){
        <?php if ($weixinPay): ?>
        setBank('<?php echo $this->getUrl('weixinpay/payment/wappay')?>','weixin_pay','<?php echo $_order->getId();?>')
        <?php else: ?>
        setBank('<?php echo $this->getUrl('alipay/payment/wapredirect')?>','alipay_mobile','<?php echo $_order->getId();?>');
        <?php endif; ?>
        jQuery("#submitbutton").click(function(){
        	jQuery.ajax({
                type: 'POST',
                url: '<?php echo $this->getUrl('sales/order/checkstatus');?>',
                data:{
                	order_id:<?php echo $_order->getId();?>
                },
                dataType: 'json',
                success: function(data){
                    if (data == 'alipay_wait_buyer_pay') {
                        go_pay();
                    } else {
                        alert('该订单已经取消');
                    }
                }
            });
        });
    });
</script>
